import * as G from './game.js';
import {drawScene,drawWorkCloseup,iconURL,portraitURL,STATIONS,MAP_POINTS,WORK_POINTS} from './art.js';
import {createActor,moveActor,updateActor} from './motion.js';
import {createEffects,emitEffect,updateEffects} from './effects.js';
import {createWorkInput,finishProgress,placeRivet,rubSurface} from './interactions.js';
import {shopStockView} from './shop-view.js';

const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(id,color,cls='')=>`<img class="${cls}" src="${iconURL(id,color)}" alt="" draggable="false">`;
const btn=(action,label,cls='secondary',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const SAVE='pix-forge-save-v1'; // Same key: v1 saves migrate through deserialize().
let state=G.newGame(Date.now()>>>0),storageOK=true,loadError=false;
try{const raw=localStorage.getItem(SAVE);if(raw)state=G.deserialize(raw);}catch(e){loadError=e instanceof G.GameError||e instanceof SyntaxError;storageOK=false;}
G.ensureOrders(state);G.ensureCustomers(state);
let view=state.trip?'explore':'forge',forgeTab='work',shopTab='stock',selected=state.work?.recipe||'lantern',metal='iron',rune='none';
let itemIndex=0,buyerId=state.customers.find(c=>!c.served)?.id,region='forest',allRecipes=false,policy='fair';
let busy=false,uiTask=null,toastTimer,audioContext,lastTick=0,lastDraw=0,workTimer=null;
const actor=createActor(222,279),npcActors=new Map(),dialog=$('#dialog'),canvas=$('#scene');
const effects=createEffects(),camera={x:240,y:160,zoom:1};
let gesture=null,lastAmbient=0;
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');

function storageNotice(){const w=$('#storage-warning');w.hidden=storageOK;w.textContent=loadError?'Сохранение не удалось прочитать. Исходный файл можно скачать в меню.':'Браузер не разрешил автосохранение. Скачай прогресс через меню перед выходом.';}
function save(){if(loadError)return;try{localStorage.setItem(SAVE,G.serialize(state));storageOK=true;$('#save-status').textContent='Прогресс сохранён на устройстве';}catch{storageOK=false;$('#save-status').textContent='Сохранение недоступно';}storageNotice();}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3800);}
function sound(kind='good'){if(!state.sound)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='triangle';o.frequency.value=kind==='hit'?210:kind==='coin'?820:510;g.gain.setValueAtTime(.05,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.16);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.17);}catch{}}
function act(fn,message){try{const result=fn();save();render();if(message)toast(typeof message==='function'?message(result):message);sound('coin');return result;}catch(e){toast(e instanceof G.GameError?e.message:'Не удалось выполнить действие.',true);if(!(e instanceof G.GameError))console.error(e);return undefined;}}
function modal(html,closable=true){$('#dialog-body').innerHTML=`<div class="modal-inner">${closable?btn('close','×','modal-close','aria-label="Закрыть"'):''}${html}</div>`;if(!dialog.open)dialog.showModal();document.body.style.overflow='hidden';}
function close(){dialog.close();document.body.style.overflow='';}
dialog.addEventListener('close',()=>document.body.style.overflow='');
dialog.addEventListener('click',e=>{if(e.target===dialog)close();});
function costsHTML(costs){return `<div class="costs">${Object.entries(costs).map(([id,n])=>`<span class="cost${state.resources[id]<n?' missing':''}">${icon(id)}${G.MATERIALS[id].name} ${n}</span>`).join('')}</div>`;}
function resources(){return `<div class="resource-strip" aria-label="Материалы">${Object.entries(state.resources).filter(([id,n])=>id!=='moon'||n||state.technologies.includes('lunar')).map(([id,n])=>`<span class="resource-chip">${icon(id)}<b>${n}</b>${G.MATERIALS[id].short||G.MATERIALS[id].name}</span>`).join('')}</div>`;}
function head(title,text,meta=''){return `<div class="section-head"><div><h1>${title}</h1><p>${text}</p></div>${meta?`<span class="section-meta">${meta}</span>`:''}</div>`;}
function currentBuyer(){return state.customers.find(c=>c.id===buyerId&&!c.served)||state.customers.find(c=>!c.served);}
function setView(next){if(busy){toast('Мастер заканчивает действие.');return;}if(!['forge','shop','orders','explore','develop'].includes(next))return;view=next;actor.path=[];actor.pose='idle';actor.speed=0;actor.x=next==='shop'||next==='orders'?307:222;actor.y=next==='shop'||next==='orders'?176:279;camera.x=240;camera.y=160;camera.zoom=1;effects.particles=[];effects.labels=[];if(next==='explore'&&state.trip){actor.x=237;actor.y=282;}render();$('#panel').scrollTop=0;if(next==='forge'&&state.work)approachStage();}
function pulse(pose,duration=430){actor.pose=pose;actor.poseStarted=performance.now();actor.workUntil=actor.poseStarted+duration;actor.facing=pose==='heat'?'left':'right';}
function performAt(station,pose,fn){if(busy)return;busy=true;render();const dest=STATIONS[station],arrive=()=>{if(pose!=='idle')pulse(pose,reduced.matches?100:600);workTimer=setTimeout(()=>{busy=false;fn();render();},reduced.matches?100:pose==='idle'?360:650);};if(Math.hypot(actor.x-dest.x,actor.y-dest.y)<2&&!actor.path.length)arrive();else{moveActor(actor,dest.x,dest.y,'forge');actor.after=arrive;}}
function approachStage(){const step=G.workStage(state);if(!step||view!=='forge'||busy)return;performAt(step.station,'idle',()=>{});}
function syncNPCs(){const waiting=state.customers.filter(c=>!c.served),chosen=currentBuyer();waiting.slice(0,4).forEach((customer,i)=>{let a=npcActors.get(customer.id);if(!a){a=createActor(56,280);a.person={...G.CLIENTS.find(p=>p.id===customer.client)};a.idleAt=performance.now()+1800+i*730;a.browseIndex=i;npcActors.set(customer.id,a);}const selected=chosen?.id===customer.id;const x=selected?244:92+i*84,y=selected?222:280+i%2*14;a.chosen=selected;a.homeX=x;a.homeY=y;if(a.targetX!==x||a.targetY!==y){moveActor(a,x,y,'shop');a.targetX=x;a.targetY=y;}});for(const [id,a]of npcActors){const customer=state.customers.find(c=>c.id===id);if(!customer){npcActors.delete(id);continue;}if(customer.served&&!a.leaving){a.leaving=true;a.person.carry=true;moveActor(a,42,282,'shop');a.after=()=>npcActors.delete(id);}}}
function gestureNPC(id){const a=npcActors.get(id);if(a){a.pose='chat';a.poseStarted=performance.now();a.workUntil=a.poseStarted+900;a.facing='down';a.idleAt=a.workUntil+2300;}}
function runtime(){return{actor,npcs:[...npcActors.values()],selectedItem:itemIndex,task:uiTask,effects,camera,reduced:reduced.matches};}
function render(){
  const m=G.mastery(state);itemIndex=Math.max(0,Math.min(itemIndex,state.stock.length-1));const buyer=currentBuyer();if(buyer)buyerId=buyer.id;
  const working=view==='forge'&&Boolean(state.work)&&forgeTab==='work';
  document.body.dataset.view=view;document.body.classList.toggle('working',working);
  document.body.dataset.workStep=working?String(state.work.step):'';
  if(working)syncTask();
  $('#hud').innerHTML=`<div class="hud-stat" aria-label="${state.gold} монет">${icon('coin')}<span>${state.gold}</span></div><div class="hud-stat" aria-label="Силы ${state.energy} из ${G.maxEnergy(state)}">${icon('energy')}<span>${state.energy}<small> / ${G.maxEnergy(state)}</small></span></div><div class="hud-stat" aria-label="Мастерство уровень ${m.level}">${icon('star')}<span>Ур. ${m.level}</span></div><div class="hud-stat day-stat">День <b>${state.day}</b></div>`;
  $('.scene-card').hidden=view==='develop';$('#guide').hidden=true;
  const sceneView=view==='orders'?'shop':view;
  $('#scene-label').textContent=sceneView==='shop'?'Лавка · зал покупателей':sceneView==='explore'?(state.trip?G.REGIONS.find(r=>r.id===state.trip.region).name:'Карта долины'):'Кузница · рабочий зал';
  $('#level-label').textContent=state.work&&view==='forge'?`Этап ${state.work.step+1} / 5`:`Мастерство ${m.level}`;
  canvas.setAttribute('aria-label',sceneView==='explore'?'Пиксельная карта леса, шахты, руин, перевала и кузницы':sceneView==='shop'?'Отдельная лавка, витрины и покупатели':'Кузница: горн, меха, инструменты, наковальня, ванна и верстак. Нажми на станцию, чтобы подойти.');
  $('#scene-actions').innerHTML=working?btn('scene-work',icon(G.workStage(state).icon),'scene-work-target',`id="scene-work-target" aria-label="${G.workStage(state).name}: выполнить действие на сцене" ${busy?'disabled':''}`):view==='forge'?Object.entries(STATIONS).map(([id,s])=>btn('station',`${icon(s.icon)}<span>${s.label}</span>`,'scene-hotspot',`data-station="${id}" style="left:${s.hotX}%;top:${s.hotY}%" aria-label="Подойти: ${s.label}"`)).join(''):view==='explore'&&!state.trip?Object.entries(MAP_POINTS).map(([id,p])=>{const open=['home','beacon'].includes(id)?id==='home'||state.ended:G.regionAvailable(state,id);const name=id==='home'?'Кузница':id==='beacon'?'Маяк':G.REGIONS.find(r=>r.id===id).name.split(' ').at(-1);return btn('map-place',`${open?'':'◆ '}${name}`,`map-pin${open?'':' locked'}${id===region?' active':''}`,`data-region="${id}" style="left:${p.x/480*100}%;top:${p.y/320*100}%" aria-label="${name}${open?'':' — пока закрыто'}"`);}).join(''):'';
  $('#end-day').hidden=Boolean(state.work||state.trip);$('#actor-status').textContent=busy?'Мастер идёт к станции и выполняет работу…':view==='forge'?'Нажми на оборудование или свободный пол':view==='shop'?'Покупатели осматривают витрины':view==='explore'?'Выбери место на карте':'';
  $('#navigation').innerHTML=[['forge','Кузница'],['shop','Лавка'],['orders','Заказы'],['explore','Карта'],['develop','Древо']].map(([id,label])=>btn('navigate',`${icon(id==='explore'?'map':id)}<span>${label}</span>` ,`nav-item${view===id?' active':''}`,`data-view="${id}" ${view===id?'aria-current="page"':''}`)).join('');
  renderGuide();$('#panel').innerHTML=({forge:forgeHTML,shop:shopHTML,orders:ordersHTML,explore:exploreHTML,develop:treeHTML}[view])();
  $('#panel').classList.toggle('work-panel',working);
  if(sceneView==='shop')syncNPCs();drawScene(canvas,state,sceneView,performance.now(),runtime());storageNotice();
  if(view==='forge'&&state.work)syncTask();if(view==='develop')requestAnimationFrame(drawTreeLines);
}
function renderGuide(){const story=G.currentStory(state);let title='Твои вещи меняют город',text='Работай, торгуй и открывай новые возможности.',action='navigate',attrs='data-view="orders"';if(state.work){title=G.workStage(state).name;text='Заготовка сохранена. Вернись в кузницу и выполни следующий этап.';attrs='data-view="forge"';}else if(state.trip){title='Тропа зовёт дальше';text='Выбери два действия и вернись с находками.';attrs='data-view="explore"';}else if(!state.energy){title='Пора отдохнуть';text='Заверши день, чтобы восстановить силы и встретить новых гостей.';action='end-day';attrs='';}else if(state.expeditions.length){title='Заказчик в пути';text='Завтра он вернётся с материалами и новостями.';action='end-day';attrs='';}else if(story){title=story.title;text=state.stock.some(i=>G.orderMatches(i,story))?'Нужная вещь готова. Передай её заказчику.':`Следующая цель: ${G.recipeById(story.recipe).name.toLowerCase()}.`;if(!state.stock.some(i=>G.orderMatches(i,story))){action='prepare';attrs=`data-order="${story.id}"`;}}else{title=state.ended?'Маяк снова горит':'Последний путь Элин';text=state.ended?'Продолжай развивать мастерскую и свою лавку.':'Заверши день, чтобы узнать о восстановлении маяка.';}$('#guide').innerHTML=`${icon('lantern')}<div><strong>${esc(title)}</strong>${esc(text)}</div>${btn(action,'→','guide-arrow',`${attrs} aria-label="${esc(title)}"`)}`;}
function forgeHTML(){
  if(state.work&&forgeTab==='work')return workHTML();
  let html=`<div class="forge-tabs segmented">${btn('forge-tab','Изделия',forgeTab==='work'?'active':'','data-tab="work"')}${btn('forge-tab','Оборудование',forgeTab==='equipment'?'active':'','data-tab="equipment"')}${btn('inventory',icon('backpack'),'inventory-button','aria-label="Запас материалов"')}</div>`;
  if(forgeTab==='equipment')return html+equipmentHTML();
  if(!G.knownMaterial(state,metal))metal='iron';if(rune!=='none'&&!state.technologies.includes('runes'))rune='none';
  const recipe=G.recipeById(selected),costs=G.craftCosts(state,selected,metal,rune),known=G.knownRecipe(state,selected);
  html+=`<div class="recipe-grid recipe-rail" aria-label="Чертежи: листай горизонтально">${G.RECIPES.map(r=>btn('select-recipe',`${icon(r.id,G.MATERIALS[metal].color)}<strong>${r.short}</strong>${G.knownRecipe(state,r.id)?'':'<span class="recipe-lock">◆</span>'}`,`recipe${selected===r.id?' selected':''}${G.knownRecipe(state,r.id)?'':' locked'}`,`data-recipe="${r.id}" aria-pressed="${selected===r.id}"`)).join('')}</div>`;
  html+=`<div class="craft-card recipe-card"><div class="item-heading"><div class="item-icon">${icon(recipe.id,G.MATERIALS[metal].color)}</div><h2>${recipe.name}</h2>${btn('recipe-info','?','info-button',`data-recipe="${recipe.id}" aria-label="Об изделии"`)}</div>${known?`<div class="craft-options"><label><span class="sr-only">Металл</span><select id="metal-select">${['iron','copper','bronze','moon'].map(id=>`<option value="${id}" ${metal===id?'selected':''} ${G.knownMaterial(state,id)?'':'disabled'}>${G.MATERIALS[id].name}${G.knownMaterial(state,id)?'':' ◆'}</option>`).join('')}</select></label><label><span class="sr-only">Руна</span><select id="rune-select">${Object.entries(G.RUNES).map(([id,r])=>`<option value="${id}" ${rune===id?'selected':''} ${id==='none'||state.technologies.includes('runes')?'':'disabled'}>${r.name}</option>`).join('')}</select></label></div>${costsHTML(costs)}${btn('begin-work',`${icon('anvil')}Начать · 2 силы`,'primary',!G.canAfford(state,costs)||state.energy<2||busy||state.trip?'disabled':'')}${state.upgrades.apprentice?`<div class="button-row apprentice-row">${btn('batch','Ученик ×1','secondary','data-count="1"')}${btn('batch','×3','secondary','data-count="3"')}</div>`:''}`:`<p class="help-text">Чертёж пока не изучен.</p>${btn('learn-recipe',`Открыть · ${recipe.learn} ◈`,'primary',`data-recipe="${recipe.id}"`)}`}</div>`;
  return html;
}
function workHTML(){
  const w=state.work,step=G.workStage(state),task=uiTask;let body='';
  const hint=['Меть в зелёной зоне — кнопкой или по заготовке.','Удерживай меха. Отпусти в зелёной зоне.','Бей в зелёной зоне — кнопкой или по наковальне.','Перетащи заготовку в выбранную среду.','Закрепи три детали.'][w.step];
  if(w.step<3){const action=['work-mark','heat-press','work-hit'][w.step],label=['Нанести метку','Держать меха','Ударить'][w.step],count=w.step===0?2:5;
    body=`${meterHTML(step.name)}${w.step===1?'':`<div class="hit-dots" id="hit-dots">${'<span></span>'.repeat(count)}</div>`}${btn(action,`<canvas id="workpiece" width="360" height="150" role="img" aria-label="Крупный вид заготовки и инструмента"></canvas>`,'work-board',`aria-label="${label}: прямо на заготовке" ${busy?'disabled':''}`)}<div class="work-controls">${btn(action,`${icon(step.icon)}${label}`,'primary'+(w.step===1?' hammer-button':''),`id="work-control" ${busy?'disabled':''}`)}${btn('stage-assist','✦','stage-assist',`aria-label="Помощь мастера: выполнить этот этап" title="Помощь мастера" ${busy?'disabled':''}`)}</div>`;
  }else if(w.step===3){body=`<div class="quench-workspace"><button class="quench-handle" id="quench-handle" aria-label="Перетащи горячую заготовку в воду, воздух или масло" ${busy?'disabled':''}>${icon(w.recipe,'#ff963e')}<span>↙ ↓ ↘</span></button><div class="quench-basins">${[['water','Вода','barrel','Качество'],['air','Воздух','wind','Лёгкость'],['oil','Масло','fire','Острота · 3 ◈']].map(([id,name,i,trait])=>btn('quench',`${icon(i)}<strong>${name}</strong><small>${trait}</small>`,'quench-basin',`data-method="${id}" ${busy||(id==='oil'&&(!state.equipment.barrel||!state.skills.includes('hardening')||state.gold<3))?'disabled':''}`)).join('')}</div></div>`;
  }else{const options=G.finishOptions(state),method=task.finishMethod,plain=method==='plain';
    body=`${options.length>1?`<div class="finish-options segmented">${options.map(o=>btn('finish-method',o.name,method===o.id?'active':'',`data-method="${o.id}" ${busy?'disabled':''}`)).join('')}</div>`:''}<div class="finish-pad" id="finish-pad" data-method="${method}" aria-label="${plain?'Закрепи три детали':'Води пальцем по поверхности изделия'}">${icon(w.recipe,G.MATERIALS[w.material].color)}${plain?`<div class="rivet-row">${[0,1,2].map(i=>btn('finish-rivet',task.rivets.includes(i)?'✓':'+',`rivet${task.rivets.includes(i)?' done':''}`,`data-rivet="${i}" aria-label="Закрепить деталь ${i+1}" ${busy||task.rivets.includes(i)?'disabled':''}`)).join('')}</div>`:'<span class="rub-arrow">⇆</span>'}<div class="finish-progress"><i id="finish-progress" style="width:${finishProgress(task)*100}%"></i></div></div>${btn('finish-tap',plain?'Закрепить деталь':'Обработать поверхность','primary',`id="work-control" ${busy?'disabled':''}`)}`;
  }
  return `<div class="work-console"><div class="work-path">${G.WORK_STAGES.map((s,i)=>`<div class="work-step${i<w.step?' done':''}${i===w.step?' current':''}" aria-label="${s.name}">${icon(s.icon)}<span>${i+1}</span></div>`).join('')}</div><div class="work-title"><h2>${step.name} <small>· ${G.recipeById(w.recipe).short}</small></h2>${btn('cancel-work-ask','×','work-cancel','aria-label="Убрать заготовку"')}</div><p class="work-hint" id="work-hint">${busy?'Мастер подходит…':w.step===4&&task.finishMethod!=='plain'?'Води пальцем по изделию, чтобы обработать его.':hint}</p><div class="work-body">${body}</div><div class="work-busy" ${busy?'':'hidden'}><span></span> Мастер работает</div></div>`;
}
function meterHTML(label){return `<div class="work-meter"><div class="meter" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="meter-target" id="meter-target"></div><div class="meter-fill" id="meter-fill"></div><div class="meter-cursor" id="meter-cursor"></div></div></div>`;}
function syncTask(){const w=state.work;if(!w)return;if(!uiTask||uiTask.step!==w.step||uiTask.day!==w.day)uiTask=createWorkInput(w,performance.now());const dots=$('#hit-dots');if(dots)[...dots.children].forEach((d,i)=>d.classList.toggle('done',i<uiTask.hits.length));const target=$('#meter-target');if(target){const width=w.step===1?.24+state.equipment.bellows*.06:.18,center=w.step===0?(uiTask.hits.length?.72:.28):.68;target.style.left=`${(center-width/2)*100}%`;target.style.width=`${width*100}%`;}}
function precision(position,target=.68){return Math.max(0,1-Math.abs(position-target)/.4);}
function completeStage(action,value){if(busy)return;const s=G.workStage(state);if(!s||s.id!==action)return;const stage=state.work.step,point=WORK_POINTS[stage];if(action==='quench'){actor.temper=value;emitEffect(effects,value==='air'?'good':'steam',...point,performance.now());}if(action==='finish')emitEffect(effects,state.work.rune==='none'?'good':'magic',...point,performance.now(),'Готово!');performAt(s.station,action==='quench'?'quench':action==='finish'?'polish':action==='heat'?'heat':'idle',()=>{uiTask=null;const item=act(()=>G.advanceWork(state,action,value));if(item)showResult(item);else if(state.work)approachStage();});}
function markOrHit(){if(busy||!state.work||!uiTask)return;const step=G.workStage(state).id;if(!['prepare','hammer'].includes(step))return;const now=performance.now();if(now-uiTask.lastHit<260)return;uiTask.lastHit=now;const score=precision(uiTask.position,step==='prepare'?(uiTask.hits.length?.72:.28):.68);uiTask.hits.push(score);pulse(step==='prepare'?'cut':'hammer');sound('hit');const point=WORK_POINTS[state.work.step],stage=state.work.step;setTimeout(()=>{if(view==='forge'&&state.work?.step===stage)emitEffect(effects,step==='hammer'?'spark':'chip',...point,performance.now(),score>.82?'Точно!':score>.55?'Хорошо':'Есть!');},reduced.matches?0:step==='hammer'?250:140);syncTask();if(uiTask.hits.length===(step==='prepare'?2:5))completeStage(step,uiTask.hits.reduce((a,b)=>a+b,0)/uiTask.hits.length);}
function startHeat(e,target){if(busy||!uiTask||state.work?.step!==1)return;if(e){e.preventDefault();target.setPointerCapture(e.pointerId);}uiTask.holding=true;uiTask.started=performance.now()-uiTask.position*2400;pulse('heat',100000);}
function releaseHeat(){if(uiTask?.holding&&state.work?.step===1){uiTask.holding=false;completeStage('heat',precision(uiTask.position));}}
function finishAction(index){if(busy||state.work?.step!==4||!uiTask)return;let done;if(uiTask.finishMethod==='plain'){index??=[0,1,2].find(i=>!uiTask.rivets.includes(i));done=placeRivet(uiTask,index);for(const b of document.querySelectorAll('[data-action="finish-rivet"]'))if(uiTask.rivets.includes(Number(b.dataset.rivet))){b.classList.add('done');b.textContent='✓';b.disabled=true;}}else done=rubSurface(uiTask,32,0);finishFeedback(done);}
function finishFeedback(done){pulse('polish',340);emitEffect(effects,uiTask.finishMethod==='sharpen'?'spark':state.work.rune==='none'?'good':'magic',...WORK_POINTS[4],performance.now());const bar=$('#finish-progress');if(bar)bar.style.width=`${finishProgress(uiTask)*100}%`;if(done)completeStage('finish',uiTask.finishMethod);}
function sceneAction(){if(busy||!state.work)return;if(state.work.step===0||state.work.step===2)markOrHit();else if(state.work.step===3)completeStage('quench','water');else if(state.work.step===4)finishAction();}
function showResult(item){const order=[G.currentStory(state),...state.orders].find(o=>o&&G.orderMatches(item,o));modal(`<p class="modal-eyebrow">Все пять этапов пройдены</p><h2 id="dialog-title">${G.itemName(item)}</h2>${icon(item.recipe,G.MATERIALS[item.material].color,'result-icon')}<div class="result-quality">Качество ${item.quality} / 100</div><div class="result-grid">${G.itemTraits(item).map(t=>`<span class="trait">${t}</span>`).join('')}<span class="trait">+12 опыта</span></div><p>${order?'Вещь подходит для заказа. Путешественник ждёт твою работу.':'Изделие готово. Покажи его покупателям в лавке.'}</p>${btn('result-go',order?'К заказчику →':'В лавку →','primary',`data-view="${order?'orders':'shop'}"`)}${btn('close','Продолжить работу','secondary','style="width:100%;margin-top:10px"')}`);}
function equipmentHTML(){return resources()+`<div class="subheading">Здание и помощник</div>${G.UPGRADES.filter(u=>u.id!=='shelves').map(u=>upgradeHTML(u)).join('')}<div class="subheading">Инструменты и станции <small>Влияют на работу и графику</small></div>${G.EQUIPMENT.map(e=>{const level=state.equipment[e.id],max=level>=e.max;return `<article class="upgrade-card"><div class="item-icon">${icon(e.icon)}</div><div><h2>${e.name} <span class="muted">${level}/${e.max}</span></h2><p>${e.desc}</p>${max?'<span class="trait">Максимум</span>':costsHTML(e.costs[level])+btn('equipment',`${level?'Улучшить':'Купить'} · ${e.prices[level]} монет`,'secondary',`data-equipment="${e.id}" ${state.gold<e.prices[level]||!G.canAfford(state,e.costs[level])||(e.need&&!state.technologies.includes(e.need))?'disabled':''}`)}${e.need&&!state.technologies.includes(e.need)?'<p class="help-text">Нужна рунная гравировка.</p>':''}</div></article>`;}).join('')}`;}
function upgradeHTML(u){const level=state.upgrades[u.id],max=level>=u.max;return `<article class="upgrade-card"><div class="item-icon">${icon(u.id==='furnace'?'forge':u.id==='bench'?'grindstone':u.id==='shelves'?'shop':'energy')}</div><div><h2>${u.name} <span class="muted">${level}/${u.max}</span></h2><p>${max?'Все улучшения установлены.':u.desc[level]}</p>${max?'<span class="trait">Готово</span>':costsHTML(u.costs[level])+btn('upgrade',`Улучшить · ${u.prices[level]} монет`,'secondary',`data-upgrade="${u.id}" ${state.gold<u.prices[level]||!G.canAfford(state,u.costs[level])||(u.need&&!state.upgrades[u.need])?'disabled':''}`)}</div></article>`;}
function shopHTML(){if(shopTab==='stock')return shopStockView(state,{buyerId,itemIndex,policy},{btn,icon,esc});const event=G.demandEvent(state);let html=head('Лавка чудес','',`${state.stock.length} вещей`)+`<div class="segmented">${[['stock','Витрина'],['materials','Закупка'],['trade','Караван'],['interior','Интерьер']].map(([id,name])=>btn('shop-tab',name,shopTab===id?'active':'',`data-tab="${id}"`)).join('')}</div>`;
  if(shopTab==='materials')return html+resources()+`<div class="subheading">Поставщик <small>${state.flags.includes('supplier')?'Скидка 15%':'Пачки по 3'}</small></div><div class="market-grid">${Object.entries(G.MATERIALS).filter(([id,m])=>m.price&&(id!=='moon'||state.flags.includes('ruins')||state.technologies.includes('lunar'))).map(([id,m])=>`<article class="material-card">${icon(id,m.color)}<div><h3>${m.name} ×3</h3><p>В запасе ${state.resources[id]}</p></div>${btn('buy-material',`${G.purchasePrice(state,id,3)} ◈`,'',`data-material="${id}" aria-label="Купить ${m.name}"`)}</article>`).join('')}</div>`;
  if(shopTab==='interior')return html+`<p class="help-text">Улучшения витрин меняют интерьер и повышают бюджет покупателей. Дополнительных посетителей открывает ветвь торговли в древе.</p>`+upgradeHTML(G.UPGRADES.find(u=>u.id==='shelves'))+btn('navigate','Открыть торговые навыки →','primary','data-view="develop"');
  if(shopTab==='trade'){const offer=G.tradeOffer(state);return html+`<div class="craft-card"><div class="item-heading"><div class="item-icon">${icon(offer.recipe,G.MATERIALS.copper.color)}</div><div><h2>${G.itemName(offer)}</h2><p>Готовый товар каравана · качество 64</p></div></div><p class="help-text">Купи, покажи подходящему гостю и перепродай с прибылью.</p><div class="craft-summary"><span>На сегодня осталось ${3-state.marketToday}</span><strong>${offer.cost} монет</strong></div>${btn('trade-buy','Купить для витрины','primary',state.gold<offer.cost||state.marketToday>=3?'disabled':'')}</div><div class="craft-card"><div class="item-heading"><div class="item-icon">${icon('relic')}</div><div><h2>Древняя находка</h2><p>Восстанови её в кузнице или открой чертёж.</p></div></div>${btn('buy-relic','Купить артефакт · 28 монет','primary',state.gold<28?'disabled':'')}</div>`;}
  return html;
}

function orderHint(o){if(!G.knownRecipe(state,o.recipe))return `Изучи чертёж «${G.recipeById(o.recipe).name}».`;if(o.rune&&!state.technologies.includes('runes'))return 'Нужны точная работа, верстак уровня 1 и рунная гравировка в древе.';if(o.material&&!G.knownMaterial(state,o.material))return o.material==='moon'?'Нужны сплавы, руны, горн уровня 2 и лунный металл.':'Нужны горн уровня 1 и искусство сплавов.';return `Материал: ${o.material?G.MATERIALS[o.material].name:'любой'}. Качество не ниже ${o.quality}${o.rune?` · руна ${G.RUNES[o.rune].name}`:''}.`;}
function orderHTML(o,story=false){const p=G.CLIENTS.find(p=>p.id===o.client),item=state.stock.filter(i=>G.orderMatches(i,o)).sort((a,b)=>a.quality-b.quality)[0];return `<article class="order-card${story?' story':''}"><div class="client-head"><img class="portrait" src="${portraitURL(p)}" alt="${p.name}"><div><h2>${esc(o.title)}</h2><p>${p.name} · ${p.role}</p></div>${story?'<span class="story-label">История</span>':''}${btn('order-info','?','info-button',`data-order="${esc(o.id)}" aria-label="Прочитать заказ"`)}</div><div class="order-requirement">${icon(o.recipe)}<div><strong>${G.recipeById(o.recipe).name}</strong><small>Качество ${o.quality}+${o.material?` · ${G.MATERIALS[o.material].name}`:''}${o.rune?` · ${G.RUNES[o.rune].name}`:''}</small></div></div><div class="reward-row"><span><b>${o.reward} монет</b> · +${story?18:12} опыта</span>${item?btn('fulfill','Передать →','',`data-order="${esc(o.id)}" data-item="${item.id}"`):btn('prepare','Подготовить →','',`data-order="${esc(o.id)}"`)}</div>${item?'':`<p class="order-hint">${esc(orderHint(o))}</p>`}</article>`;}
function ordersHTML(){const story=G.currentStory(state);return head('Заказы и истории','Твои изделия помогают горожанам.',`${state.storyIndex}/5 глав`)+state.expeditions.map(e=>`<div class="pending-card">${icon('explore')}<div>Заказчик в пути. Вернётся в день ${e.due} с новостями и ресурсами.</div></div>`).join('')+(story?orderHTML(story,true):`<div class="event-card">${icon('crown')}<div><strong>${state.ended?'Маяк восстановлен':'Элин в последней экспедиции'}</strong><p>Кузница продолжает работать. Впереди новые заказы и навыки.</p></div></div>`)+`<div class="subheading">Повседневные заказы</div>`+state.orders.map(o=>orderHTML(o)).join('');}
function prepareOrder(id){const o=[G.currentStory(state),...state.orders].find(o=>o?.id===id);if(!o)return;selected=o.recipe;forgeTab='work';if(!G.knownRecipe(state,o.recipe)||(o.material&&!G.knownMaterial(state,o.material))||(o.rune&&!state.technologies.includes('runes'))){setView('develop');toast(orderHint(o));}else{metal=o.material||'iron';rune=o.rune||'none';setView('forge');}}
function exploreHTML(){let html=head(state.trip?'Экспедиция':'Долина за порогом',state.trip?'Выбирай, на что потратить время в пути.':'Нажми на место на пиксельной карте.','2 силы');if(state.trip){const t=state.trip;html+=`<div class="craft-card"><p class="modal-eyebrow">${t.step===0?'Первая остановка':'Вторая остановка'} · ${G.REGIONS.find(r=>r.id===t.region).name}</p><h2>${t.step===0?'Куда направиться?':'Что исследовать перед возвращением?'}</h2><p class="help-text">${t.step===0?'У дороги видны следы руды, старые тайники и лагерь путника.':'Первый выбор сделан. Собери ещё находки или помоги встретившемуся человеку.'}</p><div class="choice-list">${G.TRIP_CHOICES.map(c=>btn('trip-action',`${icon(c.icon)}<span>${c.name}<small>${c.desc}</small></span>`,'choice-button',`data-choice="${c.id}"`)).join('')}</div>${t.step?`<div class="loot-grid">${Object.entries(t.found).map(([id,n])=>`<div>${icon(id)}+${n}</div>`).join('')}</div>`:''}</div>${btn('retreat-ask','Вернуться без находок','secondary danger')}`;return html;}
  const r=G.REGIONS.find(r=>r.id===region),open=G.regionAvailable(state,region),hint={mine:'Открой шахту заказом Миры или улучши горн.',ruins:'Нужны рунная гравировка, язык древних или заказ Ады.',pass:'Изучи лунную металлургию в древе.'}[region];
  html+=`<div class="region-tabs">${G.REGIONS.map(r=>btn('select-region',`${icon(r.id==='forest'?'wood':r.id==='mine'?'pickaxe':r.id==='ruins'?'relic':'moon')}<span>${r.name}</span>`,`region-tab${r.id===region?' selected':''}${G.regionAvailable(state,r.id)?'':' locked'}`,`data-region="${r.id}"`)).join('')}</div><div class="craft-card"><p class="modal-eyebrow">${open?'Путь открыт':'Пока недоступно'}</p><h2>${r.name}</h2><p class="help-text">${r.subtitle}. ${open?'Две остановки: сбор, поиск тайников или помощь путникам.':hint}</p>${btn('begin-trip',open?'Отправиться · 2 силы':'Путь закрыт','primary',`data-region="${r.id}" ${open&&state.energy>=2&&!state.work?'':'disabled'}`)}</div><div class="subheading">Древние находки <small>${state.relics.length} / 20</small></div>`;
  html+=state.relics.length?state.relics.map(r=>`<article class="relic-card"><div class="item-heading"><div class="item-icon">${icon('relic')}</div><div><h2>Старый ${G.recipeById(r.recipe).short.toLowerCase()}</h2><p>Реставрация — пять этапов в кузнице.</p></div></div><p class="help-text">Восстановить: 8 монет, дерево ×2, уголь ×1, 1 сила. Изучить: чертёж. Разобрать: железо ×3, кристаллы ×2.</p><div class="button-row">${btn('restore-relic','Восстановить','secondary',`data-relic="${r.id}"`)}${btn('process-relic','Изучить','secondary',`data-relic="${r.id}" data-process="study"`)}${btn('process-relic','Разобрать','secondary',`data-relic="${r.id}" data-process="salvage"`)}</div></article>`).join(''):'<p class="help-text">Артефакты находятся в руинах и продаются у каравана.</p>';return html;
}
function treeHTML(){const m=G.mastery(state);return head('Древо мастерства','Ремесло, торговля и открытие долины.',`Уровень ${m.level}`)+`<div class="mastery-card"><div><strong>${m.points}</strong><span>очков мастерства</span></div><div class="xp-info"><b>${state.xp} опыта</b><span>${m.progress} / 30 до нового уровня</span><div class="xp-bar"><i style="width:${m.progress/30*100}%"></i></div></div></div><p class="help-text">Каждые 30 опыта дают 1 очко. Работа: +12, продажа гостю: +6, сюжетный заказ: +18. Навыки требуют очков, монет и 1 силы.</p><div class="tree-branches"><span>Ремесло</span><span>Торговля</span><span>Путешествия</span></div><div class="skill-tree" id="skill-tree"><svg id="tree-lines" aria-hidden="true"></svg>${G.SKILLS.map(s=>{const status=G.skillStatus(state,s.id);return btn('skill-detail',`${icon(s.icon)}<strong>${s.name}</strong><small>${status==='learned'?'✓ Открыто':`${s.points} оч. · ${s.cost} ◈`}</small>`,`skill-node ${status}`,`data-skill="${s.id}" style="grid-column:${s.col+1};grid-row:${s.row+1}" aria-label="${s.name} — ${status==='learned'?'открыто':status==='available'?'доступно':'закрыто'}"`);}).join('')}</div><div class="tree-legend"><span>● Открыто</span><span>● Доступно</span><span>● Закрыто</span></div><div class="button-row">${btn('equipment-go','Оборудование кузницы →','secondary')}</div><div class="subheading" id="blueprint-list">Чертежи <small>Можно находить в тайниках</small></div>${G.RECIPES.filter(r=>!r.starter).map(r=>`<article class="technology">${icon(r.id)}<div><h2>${r.name}</h2><p>${r.desc}</p></div>${G.knownRecipe(state,r.id)?'<span class="trait">Изучен</span>':btn('learn-recipe',`${r.learn} ◈`,'secondary',`data-recipe="${r.id}" ${state.gold<r.learn||!state.energy?'disabled':''}`)}</article>`).join('')}<div class="subheading">Дневник мастерской</div><div class="journal">${state.log.slice(0,12).map(e=>`<div class="journal-entry"><time>День ${e.day}</time><p>${esc(e.text)}</p></div>`).join('')}</div>`;}
function drawTreeLines(){const tree=$('#skill-tree'),svg=$('#tree-lines');if(!tree||!svg)return;const base=tree.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${base.width} ${base.height}`);svg.innerHTML=G.SKILLS.flatMap(s=>s.parents.map(p=>{const from=tree.querySelector(`[data-skill="${p}"]`).getBoundingClientRect(),to=tree.querySelector(`[data-skill="${s.id}"]`).getBoundingClientRect();const x1=from.left-base.left+from.width/2,y1=from.bottom-base.top,x2=to.left-base.left+to.width/2,y2=to.top-base.top;const learned=G.skillStatus(state,s.id)==='learned';return `<path d="M ${x1} ${y1} C ${x1} ${(y1+y2)/2}, ${x2} ${(y1+y2)/2}, ${x2} ${y2}" class="${learned?'learned':''}"/>`;})).join('');}
function skillDetail(id){const s=G.SKILLS.find(s=>s.id===id),status=G.skillStatus(state,id),m=G.mastery(state);modal(`<p class="modal-eyebrow">${{root:'Начало пути',craft:'Ветвь ремесла',trade:'Ветвь торговли',travel:'Ветвь путешествий'}[s.branch]}</p><h2 id="dialog-title">${s.name}</h2>${icon(s.icon,undefined,'result-icon')}<p>${s.desc}</p><div class="report"><p>Предыдущие навыки: ${s.parents.map(id=>G.SKILLS.find(s=>s.id===id).name).join(', ')||'не требуются'}.</p>${s.need?`<p>Нужен ${s.need==='furnace'?'горн':'верстак'} уровня ${s.level} (у тебя ${state.upgrades[s.need]}).</p>`:''}<p>${s.points} оч. мастерства · ${s.cost} монет · 1 сила. У тебя ${m.points} оч.</p></div>${status==='learned'?'<span class="trait">Навык уже открыт</span>':btn('learn-skill','Открыть навык','primary',`data-skill="${id}" ${status==='available'&&m.points>=s.points&&state.gold>=s.cost&&state.energy?'':'disabled'}`)}${status==='locked'?btn('equipment-go','Оборудование и требования →','secondary','style="width:100%;margin-top:10px"'):''}`);}
function finishDay(){if(busy)return;const reports=act(()=>G.endDay(state));if(!reports)return;npcActors.clear();buyerId=state.customers[0].id;modal(`<p class="modal-eyebrow">Утро в долине</p><h2 id="dialog-title">День ${state.day}</h2><p>Силы восстановлены. В лавку пришли новые покупатели.</p><div class="event-card">${icon('star')}<div><strong>${G.demandEvent(state).name}</strong><p>${G.demandEvent(state).text}</p></div></div>${reports.map(r=>`<div class="report"><div class="report-head"><img src="${portraitURL(G.CLIENTS.find(p=>p.id===r.client))}" alt=""><strong>Новости от ${r.clientName}</strong></div><p>${r.returnText}</p><div class="loot-grid">${Object.entries(r.returns).map(([id,n])=>`<div>${icon(id)}+${n}</div>`).join('')}</div></div>`).join('')}${btn('close','Начать новый день','primary')}`);}
function showHaggle(){const c=currentBuyer(),item=state.stock[itemIndex];if(!c||!item)return;const q=G.customerQuote(state,item,c.id,policy);modal(`<p class="modal-eyebrow">Разговор о цене</p><h2 id="dialog-title">Торг с ${G.CLIENTS.find(p=>p.id===c.client).name}</h2><p>${G.itemName(item)} · ${c.attempts} из 2 попыток использовано.${state.skills.includes('appraisal')?` Покупатель даст до ${q.budget} монет.`:''}</p><label class="field-label" for="offer-price">Твоя цена в монетах</label><input id="offer-price" class="offer-input" type="number" min="1" max="100000" value="${q.price}">${btn('offer','Предложить цену','primary',c.attempts>=2?'disabled':'')}<p class="modal-note">Слишком высокая цена расходует попытку торга. Можно вернуться к обычной цене или выбрать другое изделие.</p>`);}
function showSettings(){if(busy)return;modal(`<p class="modal-eyebrow">Твоя кузница</p><h2 id="dialog-title">Настройки и прогресс</h2><div class="settings-row"><div>Звуки работы</div>${btn('sound',state.sound?'Включены':'Выключены','secondary')}</div><div class="settings-row"><div>Скачать сохранение<small>Все вещи, навыки и незавершённые этапы</small></div>${btn('export','Скачать','secondary')}</div>${loadError?`<div class="settings-row"><div>Исходный файл</div>${btn('export-original','Скачать','secondary')}</div>`:''}<div class="settings-row"><div>Загрузить прогресс</div>${btn('import','Выбрать','secondary')}</div><div class="settings-row"><div>Как играть</div>${btn('help','Открыть','secondary')}</div><div class="settings-row"><div>Начать заново</div>${btn('reset-ask','Сбросить','secondary danger')}</div><p class="modal-note">Сохранения первой версии переносятся автоматически. Прогресс хранится в этом браузере. Перед очисткой данных скачай его. Для установки выбери «На экран Домой» в меню браузера.</p>`);}
function exportSave(original=false){let raw;try{raw=original?localStorage.getItem(SAVE):G.serialize(state);}catch{toast('Не удалось прочитать файл.',true);return;}const url=URL.createObjectURL(new Blob([raw||''],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=original?'pix-original.json':`pix-day-${state.day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function help(){modal(`<p class="modal-eyebrow">Мастерская оживает</p><h2 id="dialog-title">Как играть</h2><ol class="modal-list"><li>Выбери чертёж, металл и руну. Возьми материалы, разметь заготовку, нагрей её мехами и нанеси пять ударов.</li><li>Выбери закалку: вода, воздух или масло. Собери, отполируй или заточи изделие. Персонаж подходит к каждой станции и работает.</li><li>В отдельной лавке поговори с гостем, пролистай витрину и предложи подходящий товар. Навык торга открывает собственную цену.</li><li>На карте выбери доступное место. За две остановки собери материалы, ищи тайники или помогай путникам.</li><li>За опыт получай очки мастерства. В древе открывай связанные навыки. Оборудование покупается во вкладке кузницы.</li><li>Выполняй сюжетные заказы и завершай день: заказчики возвращаются и открывают новые места.</li></ol><p>На рабочем этапе есть помощь мастера без проверки реакции. Она проходит только текущий этап. Клавиатура: пробел — рабочая кнопка, стрелки — ходьба.</p>${btn('close','К работе','primary')}`);}
document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target||target.disabled)return;const d=target.dataset;
  if(d.action==='heat-press'||(d.action==='scene-work'&&state.work?.step===1))return;
  if(busy&&!['close'].includes(d.action)){toast('Дождись завершения движения и работы.');return;}
  switch(d.action){
    case'navigate':setView(d.view);break;
    case'close':close();break;
    case'welcome-start':state.welcomed=true;save();close();break;
    case'forge-tab':forgeTab=d.tab;render();break;
    case'inventory':modal(`<h2 id="dialog-title">Материалы</h2><div class="inventory-grid">${Object.entries(state.resources).map(([id,n])=>`<div>${icon(id)}<strong>${n}</strong><span>${G.MATERIALS[id].name}</span></div>`).join('')}</div>${btn('close','Закрыть','primary')}`);break;
    case'recipe-info':{const r=G.recipeById(d.recipe);modal(`<h2 id="dialog-title">${r.name}</h2>${icon(r.id,G.MATERIALS[metal].color,'result-icon')}<p>${r.desc}</p><p>Ручная работа · пять этапов · +12 опыта.</p>${btn('close','К работе','primary')}`);break;}
    case'select-recipe':selected=d.recipe;render();break;
    case'all-recipes':allRecipes=!allRecipes;render();break;
    case'begin-work':if(act(()=>G.beginWork(state,selected,metal,rune))!==undefined)approachStage();break;
    case'station':{const s=STATIONS[d.station];moveActor(actor,s.x,s.y);if(state.work&&G.workStage(state).station!==d.station)toast(`Сейчас нужен ${STATIONS[G.workStage(state).station].label.toLowerCase()}.`);else toast(`Мастер подходит: ${s.label}.`);break;}
    case'work-mark':case'work-hit':markOrHit();break;
    case'scene-work':sceneAction();break;
    case'stage-assist':{const stage=G.workStage(state);if(stage&&state.work.step<3)completeStage(stage.id,.5);break;}
    case'quench':completeStage('quench',d.method);break;
    case'finish-method':if(uiTask){uiTask.finishMethod=d.method;uiTask.rivets=[];uiTask.rubDistance=0;render();}break;
    case'finish-rivet':finishAction(Number(d.rivet));break;
    case'finish-tap':finishAction();break;
    case'cancel-work-ask':modal(`<h2 id="dialog-title">Убрать заготовку?</h2><p>До разметки возвращаются материалы и силы. После разметки возвращается половина металла; остальные материалы и силы уже потрачены.</p>${btn('cancel-work','Убрать заготовку','primary gold')}${btn('close','Продолжить работу','secondary','style="width:100%;margin-top:10px"')}`);break;
    case'cancel-work':act(()=>G.cancelWork(state));uiTask=null;close();render();break;
    case'batch':act(()=>G.batchCraft(state,selected,metal,rune,Number(d.count)),items=>`Ученик изготовил ${items.length} вещей.`);break;
    case'equipment':act(()=>G.buyEquipment(state,d.equipment),'Оборудование установлено.');break;
    case'upgrade':act(()=>G.upgrade(state,d.upgrade),'Мастерская улучшена.');break;
    case'equipment-go':close();forgeTab='equipment';setView('forge');break;
    case'skill-detail':skillDetail(d.skill);break;
    case'learn-skill':if(act(()=>G.learnSkill(state,d.skill),'Новый навык открыт.')!==undefined||G.skillStatus(state,d.skill)==='learned'){close();render();}break;
    case'learn-recipe':act(()=>G.learnRecipe(state,d.recipe),'Чертёж изучен.');break;
    case'shop-tab':shopTab=d.tab;render();break;
    case'buyer-info':{const c=currentBuyer();if(c){const p=G.CLIENTS.find(p=>p.id===c.client);modal(`<h2 id="dialog-title">${p.name} · ${p.role}</h2><img class="portrait" src="${portraitURL(p)}" alt=""><p>${c.greeted?G.customerLine(c):'Познакомься с гостем, чтобы узнать его предпочтения.'}</p><p>Качество ${c.quality}+ · отношения ${state.rapport[p.id]||0}${state.skills.includes('appraisal')?` · ${c.wallet} монет`:''}</p>${btn('close','В лавку','primary')}`);}break;}
    case'demand-info':{const e=G.demandEvent(state);modal(`<h2 id="dialog-title">${e.name}</h2><p>${e.text}</p>${btn('close','В лавку','primary')}`);break;}
    case'policy':policy=d.policy;render();break;
    case'buy-material':act(()=>G.buyMaterial(state,d.material,3),`Куплено: ${G.MATERIALS[d.material].name} ×3.`);break;
    case'trade-buy':act(()=>G.buyTradeItem(state),'Товар каравана на витрине.');break;
    case'buy-relic':act(()=>G.buyRelic(state),'Находка ждёт в разделе карты.');break;
    case'select-buyer':buyerId=d.buyer;render();break;
    case'greet':{const c=currentBuyer();if(c){act(()=>G.greetCustomer(state,c.id,d.approach));gestureNPC(c.id);emitEffect(effects,'good',244,180,performance.now());}break;}
    case'item-prev':itemIndex=(itemIndex-1+state.stock.length)%state.stock.length;render();break;
    case'item-next':itemIndex=(itemIndex+1)%state.stock.length;render();break;
    case'serve':{const c=currentBuyer(),item=state.stock[itemIndex];if(c&&item){const sale=act(()=>G.serveCustomer(state,c.id,item.id,policy));if(sale)emitEffect(effects,'coin',244,183,performance.now(),`+${sale.price} ◈`);}break;}
    case'haggle':showHaggle();break;
    case'offer':{const c=currentBuyer(),item=state.stock[itemIndex],offer=Number($('#offer-price').value);if(c&&item){const result=act(()=>G.serveCustomer(state,c.id,item.id,policy,offer));if(result?.accepted){close();toast(`Сделка заключена за ${result.price} монет.`);}else if(result){showHaggle();toast('Покупатель отказался. Попробуй меньшую цену.',true);}}break;}
    case'invite':{const c=act(()=>G.inviteCustomer(state),'Новый посетитель вошёл в лавку.');if(c){buyerId=c.id;render();}break;}
    case'order-info':{const o=[G.currentStory(state),...state.orders].find(o=>o?.id===d.order);if(o)modal(`<h2 id="dialog-title">${esc(o.title)}</h2><p>${esc(o.text)}</p>${btn('close','К заказу','primary')}`);break;}
    case'prepare':prepareOrder(d.order);break;
    case'fulfill':act(()=>G.fulfill(state,d.order,Number(d.item)),o=>`Заказ выполнен! +${o.reward} монет.`);break;
    case'map-place':if(d.region==='home'){setView('forge');}else if(d.region==='beacon'){setView('orders');toast(state.ended?'Маяк восстановлен твоей работой.':'Маяк откроется в финале истории Элин.');}else{region=d.region;render();}break;
    case'select-region':region=d.region;render();break;
    case'begin-trip':if(act(()=>G.beginTrip(state,d.region))!==undefined){actor.x=225;actor.y=290;moveActor(actor,237,264);render();}break;
    case'trip-action':{const report=act(()=>G.tripAction(state,d.choice));pulse(d.choice==='gather'?'hammer':d.choice==='search'?'cut':'idle');if(report)modal(`<p class="modal-eyebrow">Возвращение из экспедиции</p><h2 id="dialog-title">Находки для кузницы</h2><div class="loot-grid">${Object.entries(report.found).map(([id,n])=>`<div>${icon(id)}${G.MATERIALS[id].name} +${n}</div>`).join('')}</div><p>+${report.xp} опыта${report.gold?` · +${report.gold} монет`:''}${report.blueprint?` · чертёж «${G.recipeById(report.blueprint).name}»`:''}${report.relic?' · древний артефакт':''}</p>${btn('close','Разложить находки','primary')}`);else if(state.trip)moveActor(actor,actor.x+12,actor.y-12);break;}
    case'retreat-ask':modal(`<h2 id="dialog-title">Вернуться сейчас?</h2><p>Потраченные силы и находки незавершённой экспедиции не вернутся.</p>${btn('retreat','Вернуться без находок','primary gold')}${btn('close','Остаться на тропе','secondary','style="width:100%;margin-top:10px"')}`);break;
    case'retreat':act(()=>G.retreatTrip(state));close();break;
    case'restore-relic':{const r=state.relics.find(r=>r.id===Number(d.relic));if(r&&act(()=>G.beginWork(state,r.recipe,'iron',state.technologies.includes('runes')?'light':'none',r.id))!==undefined){forgeTab='work';setView('forge');}break;}
    case'process-relic':act(()=>G.processRelic(state,Number(d.relic),d.process),'Находка использована.');break;
    case'end-day':finishDay();break;
    case'result-go':close();setView(d.view);break;
    case'sound':state.sound=!state.sound;save();showSettings();sound();break;
    case'export':exportSave();break;
    case'export-original':exportSave(true);break;
    case'import':$('#import-file').click();break;
    case'help':help();break;
    case'reset-ask':modal(`<h2 id="dialog-title">Начать заново?</h2><p>Все вещи, навыки и монеты будут сброшены. Сначала можно скачать сохранение.</p>${btn('export','Скачать текущий прогресс','secondary','style="width:100%;margin:10px 0"')}${btn('reset','Начать новую игру','primary gold')}${btn('close','Отмена','secondary','style="width:100%;margin-top:10px"')}`);break;
    case'reset':state=G.newGame(Date.now()>>>0);state.welcomed=true;G.ensureOrders(state);G.ensureCustomers(state);loadError=false;uiTask=null;npcActors.clear();selected='lantern';metal='iron';rune='none';forgeTab='work';shopTab='stock';itemIndex=0;save();close();setView('forge');break;
  }
});
document.addEventListener('pointerdown',e=>{
  if(busy||dialog.open||!uiTask||view!=='forge')return;
  const heat=e.target.closest('[data-action="heat-press"]')||(state.work?.step===1&&e.target.closest('[data-action="scene-work"]'));
  if(heat){startHeat(e,heat);return;}
  const handle=e.target.closest('#quench-handle'),pad=e.target.closest('#finish-pad');
  if(handle&&state.work?.step===3){e.preventDefault();handle.setPointerCapture(e.pointerId);gesture={kind:'quench',target:handle,id:e.pointerId,x:e.clientX,y:e.clientY};uiTask.dragging=true;handle.classList.add('dragging');}
  else if(pad&&state.work?.step===4&&uiTask.finishMethod!=='plain'&&!e.target.closest('button')){e.preventDefault();pad.setPointerCapture(e.pointerId);gesture={kind:'rub',target:pad,id:e.pointerId,x:e.clientX,y:e.clientY};pad.classList.add('rubbing');}
});
document.addEventListener('pointermove',e=>{
  if(!gesture||gesture.id!==e.pointerId||busy||!uiTask)return;
  if(gesture.kind==='quench'){
    gesture.target.style.transform=`translate(${e.clientX-gesture.x}px,${e.clientY-gesture.y}px)`;
    const drop=document.elementsFromPoint(e.clientX,e.clientY).find(el=>el.matches?.('.quench-basin:not(:disabled)'));
    for(const el of document.querySelectorAll('.quench-basin'))el.classList.toggle('drop-target',el===drop);
  }else if(state.work?.step===4){
    const done=rubSurface(uiTask,e.clientX-gesture.x,e.clientY-gesture.y);gesture.x=e.clientX;gesture.y=e.clientY;
    if(performance.now()-(uiTask.lastRubFX||0)>70||done){uiTask.lastRubFX=performance.now();finishFeedback(done);}
    else {const bar=$('#finish-progress');if(bar)bar.style.width=`${finishProgress(uiTask)*100}%`;}
    if(done){gesture.target.classList.remove('rubbing');gesture=null;}
  }
});
function clearGesture(){if(gesture){gesture.target.classList.remove('dragging','rubbing');gesture.target.style.transform='';}for(const el of document.querySelectorAll('.drop-target'))el.classList.remove('drop-target');if(uiTask)uiTask.dragging=false;gesture=null;}
document.addEventListener('pointerup',e=>{
  releaseHeat();if(!gesture||gesture.id!==e.pointerId)return;
  const drop=gesture.kind==='quench'?document.elementsFromPoint(e.clientX,e.clientY).find(el=>el.matches?.('.quench-basin:not(:disabled)')):null;
  clearGesture();if(drop&&state.work?.step===3)completeStage('quench',drop.dataset.method);
});
document.addEventListener('pointercancel',()=>{clearGesture();if(uiTask)uiTask.holding=false;if(actor.pose==='heat'){actor.pose='idle';actor.workUntil=0;}});
document.addEventListener('keydown',e=>{if(dialog.open)return;if(e.code==='Space'&&state.work&&view==='forge'&&!e.repeat&&!busy&&e.target.tagName!=='SELECT'){e.preventDefault();if(state.work.step===1)startHeat();else if(state.work.step===4)finishAction();else if(state.work.step===3)completeStage('quench','water');else markOrHit();}if(e.code.startsWith('Arrow')&&['forge','shop'].includes(view)&&!busy&&!state.work&&e.target===document.body){e.preventDefault();const d={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-18],ArrowDown:[0,18]}[e.code];if(d)moveActor(actor,Math.max(45,Math.min(430,actor.x+d[0])),Math.max(264,Math.min(296,actor.y+d[1])),view);}});
document.addEventListener('keyup',e=>{if(e.code==='Space')releaseHeat();});
document.addEventListener('change',e=>{if(e.target.id==='metal-select'){metal=e.target.value;render();}if(e.target.id==='rune-select'){rune=e.target.value;render();}});
let swipeStart=null;
document.addEventListener('pointerdown',e=>{if(e.target.closest('#showcase')&&!e.target.closest('button,input'))swipeStart={x:e.clientX,y:e.clientY};});
document.addEventListener('pointerup',e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)&&state.stock.length){itemIndex=(itemIndex+(dx<0?1:-1)+state.stock.length)%state.stock.length;render();}});
canvas.addEventListener('click',e=>{if(busy||!['forge','shop'].includes(view)||state.work&&view==='forge')return;const bounds=canvas.getBoundingClientRect(),x=(e.clientX-bounds.left)/bounds.width*480,y=(e.clientY-bounds.top)/bounds.height*320;if(y>263)moveActor(actor,Math.max(44,Math.min(434,x)),Math.max(270,Math.min(295,y)),view);});
$('#menu-button').addEventListener('click',showSettings);$('#tech-button').addEventListener('click',()=>setView('develop'));$('#end-day').addEventListener('click',finishDay);
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file||busy)return;try{if(file.size>250000)throw new G.GameError('Файл слишком большой.');const imported=G.deserialize(await file.text());modal(`<h2 id="dialog-title">Загрузить день ${imported.day}?</h2><p>${imported.gold} монет · уровень ${G.mastery(imported).level} · ${imported.storyIndex} глав. Текущий прогресс будет заменён.</p>${btn('export','Скачать текущий прогресс','secondary','style="width:100%;margin:10px 0"')}<button class="primary" id="confirm-import">Загрузить сохранение</button>${btn('close','Отмена','secondary','style="width:100%;margin-top:10px"')}`);$('#confirm-import').addEventListener('click',()=>{state=imported;state.welcomed=true;loadError=false;uiTask=null;npcActors.clear();save();close();setView(state.trip?'explore':'forge');},{once:true});}catch(e){toast(e instanceof G.GameError?e.message:'Не удалось прочитать сохранение.',true);}});
function animate(t){
  const dt=lastTick?Math.min(.05,(t-lastTick)/1000):.016;lastTick=t;
  if(!document.hidden){
    updateActor(actor,dt,t);updateEffects(effects,dt);
    for(const a of ['shop','orders'].includes(view)?npcActors.values():[]){
      updateActor(a,dt,t);
      if(['shop','orders'].includes(view)&&!a.leaving&&!a.path.length&&a.pose==='idle'&&t>a.idleAt){
        a.browseIndex++;a.idleAt=t+3100+(a.browseIndex%4)*650;
        if(a.chosen){a.facing=a.browseIndex%3?'down':'left';a.pose='chat';a.workUntil=t+700;}
        else moveActor(a,Math.max(67,Math.min(408,a.homeX+Math.sin(a.browseIndex*2.1)*18)),a.homeY-10+(a.browseIndex%2)*10,'shop');
      }
    }
    const working=view==='forge'&&state.work&&forgeTab==='work';
    const zoom=working?(actor.path.length?1.14:1.35):1,point=working?WORK_POINTS[state.work.step]:[240,160];
    const cx=working?Math.max(240/zoom,Math.min(480-240/zoom,(point[0]+actor.x)/2)):240;
    const cy=working?Math.max(160/zoom,Math.min(320-160/zoom,(point[1]+actor.y-20)/2)):160;
    const ease=reduced.matches?1:1-Math.exp(-dt*6);camera.x+=(cx-camera.x)*ease;camera.y+=(cy-camera.y)*ease;camera.zoom+=(zoom-camera.zoom)*ease;
    const sceneControl=$('#scene-work-target');if(sceneControl&&working){
      sceneControl.style.left=`${((point[0]-camera.x)*camera.zoom+240)/480*100}%`;
      sceneControl.style.top=`${((point[1]-28-camera.y)*camera.zoom+160)/320*100}%`;
    }
    if(working&&uiTask&&!busy&&!dialog.open&&state.work.step<3){
      if(state.work.step===1){if(uiTask.holding)uiTask.position=Math.min(1,(t-uiTask.started)/2400);else uiTask.position=Math.max(0,uiTask.position-dt*.06);}
      else uiTask.position=(Math.sin((t-uiTask.started)/620-Math.PI/2)+1)/2;
      const cursor=$('#meter-cursor'),fill=$('#meter-fill');if(cursor){cursor.style.left=`${Math.min(99,uiTask.position*100)}%`;cursor.parentElement.setAttribute('aria-valuenow',Math.round(uiTask.position*100));}if(fill)fill.style.width=state.work.step===1?`${uiTask.position*100}%`:'0%';
      if(uiTask.holding&&t-lastAmbient>180){lastAmbient=t;emitEffect(effects,'ember',187,150,t);}
    }
    const active=working||actor.path.length||[...npcActors.values()].some(a=>a.path.length)||effects.particles.length;
    if(t-lastDraw>(reduced.matches?42:active?16:50)&&view!=='develop'){drawScene(canvas,state,view==='orders'?'shop':view,reduced.matches?0:t,runtime());if(working&&state.work.step<3)drawWorkCloseup($('#workpiece'),state,runtime(),reduced.matches?0:t);lastDraw=t;}
  }requestAnimationFrame(animate);
}
window.addEventListener('resize',drawTreeLines);
window.addEventListener('blur',()=>{clearGesture();if(uiTask)uiTask.holding=false;if(actor.pose==='heat'){actor.pose='idle';actor.workUntil=0;}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearGesture();if(uiTask)uiTask.holding=false;save();}});
window.addEventListener('pagehide',save);
render();save();requestAnimationFrame(animate);
if(!state.welcomed&&!loadError){modal(`<p class="modal-eyebrow">Кузница чудес · живая мастерская</p><h2 id="dialog-title">Каждая вещь —<br>работа твоих рук</h2><canvas class="welcome-art" width="480" height="320" id="welcome-scene" aria-label="Кузница с детализированным кузнецом"></canvas><ul class="welcome-points"><li>${icon('anvil')}Пять этапов ремесла и рабочие станции</li><li>${icon('handshake')}Покупатели, вкусы и торг</li><li>${icon('map')}Карта, экспедиции и древо мастерства</li></ul>${btn('welcome-start','Начать с первого фонаря','primary')}<p class="modal-note">Прогресс старой версии сохраняется. Играй в своём темпе.</p>`,false);drawScene($('#welcome-scene'),state,'forge',0);}
if(state.work&&!dialog.open)approachStage();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
