import * as J from './jewelry.js';
import {JewelEditor} from './jewel-editor.js';
import {jewelURL} from './jewel-art.js';
import {AtelierScene,paintMap} from './atelier-scene.js';
import {paintPortrait} from './characters.js';
import {GameAudio} from './audio.js';
import {loadAtelier,saveAtelier} from './atelier-store.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(action,text,cls='',attrs='')=>`<button data-action="${action}" class="${cls}" ${attrs}>${text}</button>`;
const SAVE='pix-forge-save-v1',portraits=new Map(),scene=new AtelierScene(),audio=new GameAudio();
let state=J.newGame(Date.now()>>>0),sourceRaw=null,loadError=false,storageOK=true,storageTimer=null;
try{let local=null;try{local=localStorage.getItem(SAVE);}catch{}let disk=null;try{disk=await loadAtelier();}catch{}const stamp=raw=>{try{return JSON.parse(raw)?.savedAt||0;}catch{return -1;}};sourceRaw=disk&&(!local||stamp(disk)>=stamp(local))?disk:local;if(sourceRaw)state=J.deserialize(sourceRaw);}catch{loadError=true;storageOK=false;}
let view='studio',supplyTab='buy',selectedType='pendant',template='oval',selectedMetal=state.materials.silver?'silver':'copper',itemIndex=0,buyerId=null,policy='fair',editor=null,toastTimer,lastFrame=0;
let editorOptions={tool:'shape',width:1,symmetry:false,gem:'garnet',cut:'round',zoom:1,pan:{x:0,y:0}};
const dialog=$('#dialog'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
function portrait(person){if(portraits.has(person.id))return portraits.get(person.id);const c=document.createElement('canvas');c.width=c.height=64;paintPortrait(c.getContext('2d'),person);const url=c.toDataURL();portraits.set(person.id,url);return url;}
function notice(){const el=$('#storage-warning');el.hidden=storageOK;el.textContent=loadError?'Сохранение повреждено. Скачай исходный файл в меню или импортируй другой.':'Автосохранение недоступно. Скачай прогресс через меню.';}
function save(){if(loadError)return;state.savedAt=Date.now();const raw=J.serialize(state);let localOK=false;try{localStorage.setItem(SAVE,raw);localOK=true;}catch{}saveAtelier(raw).then(()=>{storageOK=true;notice();}).catch(()=>{storageOK=localOK;notice();});storageOK=localOK;notice();}
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.className='toast show'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3300);}
function action(fn,message){try{editor?.finish();const result=fn();save();render();audio.play('good');if(message)toast(typeof message==='function'?message(result):message);return result;}catch(e){toast(e.message||'Действие не выполнено.',true);audio.play('error');if(!(e instanceof J.AtelierError))console.error(e);}}
function modal(title,body,closable=true){$('#dialog-body').innerHTML=`<div class="modal-title"><h2 id="dialog-title">${title}</h2>${closable?btn('close','×','','aria-label="Закрыть"'):''}</div><div class="modal-body">${body}</div>`;if(!dialog.open)dialog.showModal();}
function close(){dialog.close();}
dialog.addEventListener('click',e=>{if(e.target===dialog&&state.welcomed)close();});
function currentBuyer(){return state.customers.find(c=>c.id===buyerId&&!c.served)||state.customers.find(c=>!c.served);}
const currentItem=()=>state.stock[Math.max(0,Math.min(itemIndex,state.stock.length-1))];
function typeIcon(type){const d=J.makeDesign(type,'oval','gold');if(!['sword','staff','ring'].includes(type))d.gems.push({kind:'amethyst',x:50,y:47,size:6,cut:'round'});return jewelURL(d,128);}
const typeName=id=>J.TYPES.find(t=>t.id===id)?.name||id;
const costText=d=>{const c=J.costs(d);return Object.entries(c.resources).map(([id,n])=>`${(J.METALS[id]||J.GEMS[id]).name} ×${n}`).join(' · ')+(c.coins?' · '+c.coins+' ◈':'');};
function sceneHTML(shop=false){return `<div class="scene-wrap${shop?'':' studio-scene'}"><canvas id="scene" width="480" height="260" aria-label="Ювелирная мастерская: стол гравировки, камни, оправы и ювелир" role="img"></canvas><span class="scene-caption">${shop?'Лавка авторских украшений':'Веленский порт · 1740'}</span></div>`;}
function render(){
 if(editor){editorOptions={tool:editor.tool,width:editor.width,symmetry:editor.symmetry,gem:editor.gem,cut:editor.cut,zoom:editor.zoom,pan:{...editor.pan}};editor.destroy();editor=null;}
 audio.setOptions(state);audio.setScene(view==='shop'||view==='orders'?'shop':view==='supplies'&&supplyTab==='map'?'explore':'forge');
 $('#hud').innerHTML=`<span>◈ <b>${state.gold}</b></span><span>✦ <b>${Math.floor(state.xp/35)+1}</b></span><span>◇ <b>${state.stock.length}</b></span><span class="day">День ${state.day}</span>`;
 $('#navigation').innerHTML=[['studio','✎','Мастерская'],['shop','◇','Витрина'],['supplies','◆','Материалы'],['orders','▤','Заказы'],['develop','✦','Развитие']].map(([id,icon,text])=>btn('navigate',`<span>${icon}</span>${text}`,view===id?'active':'',`data-view="${id}" ${view===id?'aria-current="page"':''}`)).join('');
 $('#panel').className='panel'+(view==='studio'&&state.draft?' editor-panel':'');$('#panel').innerHTML=({studio:studioHTML,shop:shopHTML,supplies:suppliesHTML,orders:ordersHTML,develop:developHTML}[view])();
 if(view==='studio'&&state.draft){editor=new JewelEditor($('#jewel-canvas'),state,{onChange:updateEditor,onCommit:()=>{save();audio.play(editor?.tool==='rune'?'magic':editor?.tool==='polish'?'polish':'rivet');updateEditor();},onError:text=>toast(text,true)});Object.assign(editor,editorOptions);editor.setWidth(editor.width);if(!state.skills.includes('facets'))editor.cut='round';editor.pan={...editorOptions.pan};editor.dirty=true;updateEditor();}
 if(view==='shop'){const buyer=currentBuyer();if(buyer)buyerId=buyer.id;const selected=$('.buyer-chip.active');selected?.scrollIntoView({block:'nearest',inline:'nearest'});}
 notice();paint(performance.now(),0);
}
function studioHTML(){
 if(state.draft)return editorHTML();
 const templates=['ring','sword','staff'].includes(selectedType)?[['oval','Оправа'],['free','Свой контур']]:[['oval','Овал'],['heart','Сердце'],['leaf','Лист'],['diamond','Ромб'],['free','Свой контур']];if(!templates.some(([id])=>id===template))template='oval';
 return sceneHTML()+`<div class="section-line"><h1>Твоё новое изделие</h1>${btn('inventory','▦','','aria-label="Запасы материалов"')}</div><div class="type-grid">${J.TYPES.map(t=>btn('select-type',`<img src="${typeIcon(t.id)}" alt=""><span>${t.short}${J.typeAvailable(state,t.id)?'':' ◆'}</span>`,`type-card${selectedType===t.id?' active':''}${J.typeAvailable(state,t.id)?'':' locked'}`,`data-type="${t.id}" aria-pressed="${selectedType===t.id}"`)).join('')}</div><div class="rail template-row" aria-label="Базовые заготовки">${templates.map(([id,name])=>btn('template',name,id===template?'active':'',`data-template="${id}"`)).join('')}</div><div class="row" style="margin-top:8px"><select id="start-metal" aria-label="Металл заготовки">${Object.entries(J.METALS).map(([id,m])=>`<option value="${id}" ${selectedMetal===id?'selected':''} ${J.available(state,id)?'':'disabled'}>${m.name} · ${state.materials[id]}</option>`).join('')}</select><small>Ресурсы списываются при завершении</small></div>${btn('start-design','✎ Создать своё изделие','primary big')}${state.library.length?`<div class="section-line"><h2>Твои модели</h2><small>${state.library.length}/40</small></div><div class="rail">${state.library.map(m=>btn('load-model',`<img src="${jewelURL(m.design,100)}" alt="">${esc(m.design.name)}`,'library-chip',`data-model="${m.id}"`)).join('')}</div>`:''}`;
}
function editorHTML(){const d=state.draft.design;
 return `<div class="editor-heading"><input id="jewel-name" maxlength="48" value="${esc(d.name)}" aria-label="Название изделия">${btn('undo','↶','','aria-label="Отменить действие"')}${btn('redo','↷','','aria-label="Повторить действие"')}${btn('editor-help','?','','aria-label="Как создавать украшение"')}</div><div id="editor-metrics" class="editor-metrics"></div><div class="editor-stage"><canvas id="jewel-canvas" aria-label="Редактор изделия. Рисуй пальцем, перетаскивай контур и камни; два пальца меняют масштаб." tabindex="0"></canvas><span id="editor-hint" class="editor-hint"></span><div class="zoom-controls">${btn('zoom-out','−','','aria-label="Уменьшить масштаб"')}${btn('zoom-reset','⊙','','aria-label="Сбросить масштаб"')}${btn('zoom-in','+','','aria-label="Увеличить масштаб"')}</div><canvas id="artist-scene" class="artist-inset" width="480" height="260" aria-label="Ювелир работает за столом" role="img"></canvas></div><div class="tools" aria-label="Инструменты">${[['shape','○','Форма'],['engrave','✎','Узор'],['stone','◆','Камни'],['rune','✦','Руны'],['polish','▥','Блеск'],['hole','◌','Вырез'],['move','↔','Сдвиг'],['erase','⌫','Убрать']].map(([id,icon,text])=>btn('editor-tool',`<span>${icon}</span>${text}`,editorOptions.tool===id?'active':'',`data-tool="${id}" title="${text}" aria-label="${text}" aria-pressed="${editorOptions.tool===id}"`)).join('')}</div><div id="tool-options" class="tool-options"></div><div class="editor-bottom">${btn('material-picker','◈','secondary','aria-label="Сменить металл и посмотреть расход"')}${btn('finish-design','Готово','primary','id="finish-design"')}${btn('remember','▤','secondary','aria-label="Сохранить модель"')}${btn('discard','×','secondary danger','aria-label="Убрать заготовку"')}</div>`;
}
function updateEditor(metrics){if(!state.draft||!$('#editor-metrics'))return;const d=editor?.design||state.draft.design,e=metrics||J.evaluate(d);$('#editor-metrics').innerHTML=`<span>Ремесло <b>${e.craft}</b></span><span>${e.label}</span><span>Магия <b>${Math.round(e.magic*(state.skills.includes('alchemy')?1.25:1))}</b></span><span>Блеск ${e.polish}%</span>`;
 const hints={shape:'Потяни точку или нарисуй новый контур',engrave:'Нанеси свой узор по металлу',stone:'Поставь камень; потяни, чтобы переместить',rune:'Проведи руну к камню: он пробудится',polish:'Обработай поверхность движениями пальца',hole:'Обведи вырез внутри металлической основы',move:'Перемещай поле; два пальца — масштаб',erase:'Коснись камня, линии или выреза'};$('#editor-hint').textContent=hints[editor?.tool||editorOptions.tool];
 const a=$('[data-action="undo"]'),b=$('[data-action="redo"]');a.disabled=!state.draft.undo.length;b.disabled=!state.draft.redo.length;
 const c=J.costs(d),afford=Object.entries(c.resources).every(([id,n])=>state.materials[id]>=n)&&state.gold>=c.coins,button=$('#finish-design');button.textContent=`Готово · ▰${c.resources[d.metal]}${d.gems.length?' ◆'+d.gems.length:''}${c.coins?' '+c.coins+'◈':''}`;button.title=costText(d);button.setAttribute('aria-label','Завершить изделие. '+costText(d));button.disabled=!afford||d.outline.length<3||!J.hasHandwork(d);if(!J.hasHandwork(d))button.textContent='Оформи заготовку';else if(!afford)button.textContent=state.gold<c.coins?'Нужны монеты':'Нужны материалы';
 const opts=$('#tool-options');if(opts.dataset.tool!==(editor?.tool||editorOptions.tool)||opts.dataset.selected!==String(editor?.selected??-1)){opts.dataset.tool=editor?.tool||editorOptions.tool;opts.dataset.selected=String(editor?.selected??-1);renderToolOptions();}
 for(const el of document.querySelectorAll('[data-action="editor-tool"]')){el.classList.toggle('active',el.dataset.tool===editor?.tool);el.setAttribute('aria-pressed',el.dataset.tool===editor?.tool?'true':'false');}
}
function renderToolOptions(){const tool=editor?.tool||editorOptions.tool,w=editor?.width||editorOptions.width;$('#tool-options').classList.toggle('has-cuts',tool==='stone'&&state.skills.includes('facets'));$('#tool-options').innerHTML=(tool==='stone'?`<select id="gem-kind" aria-label="Камень">${Object.entries(J.GEMS).filter(([id])=>J.available(state,id)).map(([id,g])=>`<option value="${id}" ${editor?.gem===id?'selected':''}>${g.name} · ${state.materials[id]}</option>`).join('')}</select>`:`<small>${tool==='shape'?'Контур':tool==='polish'?'Кисть':'Линия'}</small>`)+`<label><span>${tool==='stone'?'Размер':'Толщина'}</span><input id="brush-width" aria-label="${tool==='stone'?'Размер камня':'Толщина линии'}" type="range" min="0.5" max="${tool==='stone'&&!state.skills.includes('facets')?3:5.5}" step="0.5" value="${w}"></label>${btn('symmetry','↔',editor?.symmetry?'active':'',`id="symmetry" aria-label="Зеркальная симметрия" aria-pressed="${!!editor?.symmetry}"`)}${tool==='stone'&&state.skills.includes('facets')?`<select id="gem-cut" aria-label="Огранка">${[['round','Круг'],['oval','Овал'],['pear','Капля']].map(([id,name])=>`<option value="${id}" ${editor?.cut===id?'selected':''}>${name}</option>`).join('')}</select>`:''}`;}
function shopHTML(){const guests=state.customers.filter(c=>!c.served),buyer=currentBuyer(),person=buyer&&J.CLIENTS.find(p=>p.id===buyer.client),item=currentItem();if(buyer)buyerId=buyer.id;
 let html=sceneHTML(true)+`<div class="rail" aria-label="Покупатели">${guests.map(c=>{const p=J.CLIENTS.find(p=>p.id===c.client);return btn('buyer',`<img src="${portrait(p)}" alt=""><b>${p.name}</b>`,`buyer-chip${buyer?.id===c.id?' active':''}`,`data-buyer="${c.id}"`);}).join('')}${!guests.length?btn('next-day','☀ Новые покупатели'):''}</div>`;
 if(person)html+=`<div class="buyer-intro"><b>${person.name}</b><span>${person.line}</span></div>`;
 if(!item)return html+`<div class="card empty"><div class="symbol">◇</div><h2>Витрина ждёт твою работу</h2><p class="muted">Форма, узор и камни сохранятся точно как ты их создал.</p>${btn('navigate','Создать украшение','primary big','data-view="studio"')}</div>`;
 const d=item.design,e=J.evaluate(d),demand=J.demandInfo(state,d),q=buyer?J.quote(state,item,buyer,policy):null;
 html+=`<div class="card"><div class="section-line"><h2>${esc(d.name)}</h2><small>${itemIndex+1}/${state.stock.length}</small></div><div class="showcase">${btn('previous','‹','','aria-label="Предыдущее изделие"')}<img src="${jewelURL(d,300)}" alt="${esc(d.name)}: авторская форма, рисунок и камни">${btn('next','›','','aria-label="Следующее изделие"')}</div><div class="metrics"><span>Мастерство<b>${e.craft}</b></span><span>Стиль<b>${e.label}</b></span><span>Магия<b>${Math.round(e.magic*(state.skills.includes('alchemy')?1.25:1))}</b></span>${q?`<span>Вкус ${person.name}<b>${q.fit}%</b></span>`:''}</div><div class="market-status${demand.remaining?' cool':''}"><span>${demand.remaining?`Спрос −75% · ещё ${demand.remaining} торговых дней`:'Продажи по полной цене: '+demand.sales+'/4'}</span><span class="demand-dots${demand.remaining?' cool':''}">${Array.from({length:4},(_,i)=>`<i class="${i<demand.sales?'on':''}"></i>`).join('')}</span>${btn('demand-info','?','','aria-label="Как работает спрос" style="min-height:27px;width:27px;padding:0"')}</div>${q?`<div class="price-row">${[['low','Доступно'],['fair','Полная цена'],['high','Дороже']].map(([id,name])=>btn('policy',name,id===policy?'active':'',`data-policy="${id}"`)).join('')}</div>${btn('sell',`Продать · ${q.price} ◈`,'primary sell-button',`data-item="${item.id}" ${q.accepted?'':'aria-describedby="buyer-refusal"'}`)}${!q.accepted?`<p id="buyer-refusal" class="muted" style="margin-top:6px">${q.reason}</p>`:''}`:`${btn('next-day','☀ Открыть лавку завтра','primary big')}`}<div class="detail-actions">${btn('item-info','Оценка работы','','data-item="'+item.id+'"')}${btn('save-item-model','▤ Модель','','data-item="'+item.id+'"')}${btn('recycle','Переплавить','danger','data-item="'+item.id+'"')}</div></div>`;return html;
}
function suppliesHTML(){let html=`<div class="section-line"><h1>Материалы</h1>${btn('inventory','▦','','aria-label="Запасы"')}</div><div class="tabs">${btn('supply-tab','Поставщик',supplyTab==='buy'?'active':'','data-tab="buy"')}${btn('supply-tab','Места находок',supplyTab==='map'?'active':'','data-tab="map"')}</div>`;
 if(supplyTab==='map')return html+`<div class="scene-wrap map-stage"><canvas id="map" width="480" height="260" aria-label="Карта мест находок: берег, сад аббатства и лунный кряж"></canvas>${J.AREAS.map(a=>btn('gather',`${state.crafted>=a.need?'':'◆ '}${a.name}`,`map-pin`, `data-area="${a.id}" style="left:${a.x/480*100}%;top:${a.y/260*100}%" ${state.energy<=0||state.daily.areas.includes(a.id)||state.crafted<a.need?'disabled':''}`)).join('')}</div><div class="card"><h2>Находки для новых работ</h2><p class="muted">Силы: ${state.energy}/4. В каждом месте можно искать один раз за день. Сад открывается после 3 изделий, кряж — после 8.</p>${btn('next-day','☀ Следующий день','big')}</div>`;
 return html+`<div class="two-grid">${Object.entries({...J.METALS,...J.GEMS}).map(([id,m])=>`<div class="card supply"><span class="swatch" style="background:${m.color}">${J.GEMS[id]?'◆':'▰'}</span><div class="copy"><b>${m.name}</b><small>В запасе ${state.materials[id]}<br>${m.price} ◈ за ${J.GEMS[id]?'камень':'порцию'}</small></div>${J.available(state,id)?btn('buy',`+${J.METALS[id]?5:1}`,'',`data-material="${id}" data-count="${J.METALS[id]?5:1}" ${state.gold<m.price*(J.METALS[id]?5:1)?'disabled':''}`):btn('locked-material','◆','','data-material="'+id+'" aria-label="Как открыть материал"')}</div>`).join('')}</div>`;
}
function ordersHTML(){return `<div class="section-line"><h1>Личные заказы</h1><small>По вкусу жителей</small></div>${state.requests.map(r=>{const p=J.CLIENTS.find(p=>p.id===r.client),item=state.stock.find(i=>J.matches(i.design,r)&&!J.demandInfo(state,i.design).remaining),style={organic:'Растительные формы',symmetry:'Симметрия',ornate:'Насыщенный узор',contrast:'Сочетание камней',minimal:'Сдержанность'}[r.style];return `<div class="card order-card"><img src="${portrait(p)}" alt="${p.name}"><div class="order-copy"><h2>${esc(r.title)}</h2><b>${p.name} · ${typeName(r.type)}</b><small>${style} ≥ ${r.min} · мастерство ≥50${r.minMagic?' · магия ≥'+r.minMagic:''}</small><small>${r.done?'Заказ выполнен':'Срок: день '+r.until+' · свежий дизайн · +15% к цене'}</small>${!r.done?(item?btn('deliver','Передать '+esc(item.design.name),'primary',`data-request="${r.id}" data-item="${item.id}"`):btn('prepare-order','Создать для заказа','',`data-type="${r.type}"`)):''}</div></div>`;}).join('')}`;}
function developHTML(){return `<div class="section-line"><h1>Искусство ювелира</h1><small>Опыт: ${state.xp}</small></div><div class="tree">${[J.TOOLS.slice(0,3),['signature','mounts','alchemy'].map(id=>J.TOOLS.find(t=>t.id===id))].map(row=>`<div class="tree-row">${row.map(t=>{const learned=state.skills.includes(t.id),ready=t.parents.every(p=>state.skills.includes(p));return btn('skill',`<span>${{eye:'◉',gold:'◈',facets:'◆',alchemy:'✦',mounts:'⚔',signature:'✎'}[t.id]}</span><b>${t.name}</b><small>${learned?'Изучено':t.cost+' ◈ · '+t.xp+' опыта'}</small>`,`skill${learned?' unlocked':ready?'':' locked'}`,`data-skill="${t.id}"`);}).join('')}</div>`).join('')}</div><div class="card"><p class="muted">Опыт даётся за создание, продажу и выполнение заказов. Масштаб, отмена, симметрия, базовая гравировка и руны доступны сразу.</p></div>`;}

function paint(time,dt){
 editor?.paint(reduced.matches?0:time);
 const inset=$('#artist-scene'),room=$('#scene'),map=$('#map');
 if(inset&&editor)scene.paint(inset.getContext('2d'),state,{design:editor.preview(),working:!!editor.operation,tool:editor.tool,time:reduced.matches?0:time,dt});
 if(room)scene.paint(room.getContext('2d'),state,{shop:view==='shop',design:view==='shop'?currentItem()?.design:null,buyerId,time:reduced.matches?0:time,dt});
 if(map)paintMap(map.getContext('2d'),state,reduced.matches?0:time);
}
function frame(time){requestAnimationFrame(frame);if(document.hidden||time-lastFrame<50)return;const dt=Math.min(.1,(time-lastFrame)/1000);lastFrame=time;paint(time,dt);}
function editorHelp(){modal('Твоя работа — твой рисунок',`<div class="help-grid"><b>○</b><span>Потяни точки заготовки или нарисуй свой замкнутый контур. «Вырез» убирает металл внутри основы.</span><b>✎</b><span>Рисуй узор по металлу. Выбирай толщину; ↔ повторяет линию зеркально.</span><b>◆</b><span>Поставь камни и передвинь их пальцем. Камень должен держаться в оправе.</span><b>✦</b><span>Проведи руну рядом с камнем: его свойство пробудится.</span><b>▥</b><span>Полируй поверхность движениями пальца. Обработанные участки светлеют.</span><b>⊙</b><span>Масштаб — двумя пальцами или +/−. «Сдвиг» передвигает поле. ↶/↷ отменяют и возвращают действия.</span></div><p class="fine-print">Ни рисунок, ни название не теряются при переходе между разделами. Материалы расходуются только после «Готово».</p>`);}
function showInventory(){modal('Твои материалы',`<div class="inventory-grid">${Object.entries({...J.METALS,...J.GEMS}).map(([id,m])=>`<span><b style="color:${m.color}">${J.GEMS[id]?'◆':'▰'}</b> ${m.name} <b>×${state.materials[id]}</b></span>`).join('')}</div>${btn('go-supplier','К поставщику','primary')}`);}
function showMaterials(){editor?.finish();const d=state.draft.design;modal('Металл и расход',`<p>${esc(costText(d))}${J.costs(d).coins?' (готовая основа оружия)':''}</p><div class="inventory-grid">${Object.entries(J.METALS).map(([id,m])=>btn('apply-metal',`<b style="color:${m.color}">▰</b> ${m.name}<br><small>Запас ${state.materials[id]}</small>`,d.metal===id?'active':'',`data-metal="${id}" ${J.available(state,id)?'':'disabled'}`)).join('')}</div><p class="fine-print">Цена и расход меняются вместе с площадью твоего контура. Можно вернуться к рисунку и уменьшить оправу.</p>`);}
function showAssessment(item,completed=false){const d=item.design,e=J.evaluate(d),effects=Object.entries(e.effects).map(([id,power])=>`${J.ELEMENTS[id]} +${Math.round(power*(state.skills.includes('alchemy')?1.25:1))}`).join(' · ');modal(completed?'Украшение готово':'Оценка работы',`<img class="hero-jewel" src="${jewelURL(d,300)}" alt="${esc(d.name)}"><h2>${esc(d.name)}</h2><div class="score-row"><span>Мастерство</span><b>${e.craft}/100</b></div><div class="score-row"><span>Художественный стиль</span><b>${e.label}</b></div><div class="score-row"><span>Магия</span><b>${Math.round(e.magic*(state.skills.includes('alchemy')?1.25:1))}</b></div>${state.skills.includes('eye')?`<p>Обработано ${e.polish}% металла. Связанных камней: ${e.connections}. ${effects||'Без пробуждённых рун.'}</p><div class="inventory-grid">${Object.entries(e.style).map(([id,n])=>`<span>${{symmetry:'Симметрия',ornate:'Богатство',organic:'Растительные формы',minimal:'Сдержанность',contrast:'Контраст'}[id]} <b>${n}</b></span>`).join('')}</div><p class="fine-print">Мастерство зависит от контура, оправ, гравировки и реальной обработки поверхности. У жителей разные вкусы: богатый узор подходит не всем.</p>`:`<p class="muted">Полировка и устойчивые оправы повышают мастерство. «Глаз мастера» открывает подробный разбор.</p>`}${completed?`<div class="row fill">${btn('completed-studio','Ещё изделие')}${btn('completed-shop','На витрину','primary')}</div>`:''}`);}
function showDemand(){modal('Спрос любит новые работы',`<p>После <b>4 продаж одного дизайна по полной или высокой цене</b> цена следующих экземпляров падает на <b>75%</b>.</p><p>Спрос восстанавливается через <b>7 торговых дней с продажами</b>. Дни без продаж этот срок не сокращают.</p><p>Название, цвет металла и небольшие правки линий не делают старый рисунок новым. Меняй форму, композицию узора и расположение камней.</p><p class="fine-print">Личные заказы тоже учитываются. Заказчики не принимают дизайн, спрос на который уже насыщен.</p>`);}
function showSkill(id){const t=J.TOOLS.find(t=>t.id===id);if(!t)return;const learned=state.skills.includes(id),parents=t.parents.filter(p=>!state.skills.includes(p));modal(t.name,`<p>${t.desc}</p>${parents.length?`<p>Сначала: ${parents.map(id=>J.TOOLS.find(t=>t.id===id).name).join(', ')}.</p>`:''}<div class="score-row"><span>Стоимость</span><b>${t.cost} ◈</b></div><div class="score-row"><span>Нужный опыт</span><b>${t.xp} / ${state.xp}</b></div><p class="fine-print">Опыт не тратится при изучении.</p>${btn('learn',learned?'Изучено':'Изучить','primary',`data-skill="${id}" ${learned||parents.length||state.gold<t.cost||state.xp<t.xp?'disabled':''}`)}`);}
function download(raw,filename){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function menu(){editor?.finish();modal('Мастерская «Сияние»',`<div class="settings">${btn('toggle-sound',`Эффекты: ${state.sound?'вкл':'выкл'}`)}${btn('toggle-music',`Музыка: ${state.music?'вкл':'выкл'}`)}<label>Громкость <input id="volume" aria-label="Громкость" type="range" min="0" max="1" step="0.05" value="${state.volume}"></label>${btn('export','Скачать сохранение')}${btn('import','Загрузить сохранение')}${state.legacy?btn('legacy-export','Скачать архив прежней игры'):''}${loadError?btn('reset-recovery','Начать заново','danger'):''}</div><p class="fine-print">Изделия и история действий сохраняются на этом устройстве. Для переноса на другой телефон скачай файл. Веленский порт, 1740 год.</p>${state.legacy?'<p class="fine-print">Монеты и запасы перенесены. Прежние товары обменены на 65% их стоимости, незавершённая работа разобрана; оригинальное сохранение доступно в архиве.</p>':''}`);}
function welcome(){modal('Добро пожаловать в «Сияние»',`<div class="welcome"><img src="./assets/icon.svg" alt=""><p>Твоя ювелирная мастерская в Веленском порту, 1740 год.</p></div><div class="help-grid"><b>✎</b><span>Придумай форму и нанеси собственный узор.</span><b>◆</b><span>Поставь камни, пробуди их рунами, отполируй оправу.</span><b>◇</b><span>Выставляй работу и ищи покупателя по вкусу. Повторяющиеся дизайны теряют спрос.</span></div>${state.legacy?'<p class="fine-print">Твой прежний прогресс перенесён, исходное сохранение сохранено в архиве.</p>':''}${btn('welcome-start','Открыть мастерскую','primary')}`,false);}
function resetEditor(){editorOptions={tool:'shape',width:1,symmetry:false,gem:'garnet',cut:'round',zoom:1,pan:{x:0,y:0}};}
function editAndRefresh(fn){try{editor?.finish();const d=J.clone(state.draft.design);fn(d);J.edit(state,d);save();editor.dirty=true;editor.metrics=J.evaluate(d);updateEditor();}catch(e){toast(e.message,true);}}
let pendingImport=null;
document.addEventListener('pointerdown',()=>{audio.unlock();},{passive:true});
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const id=b.dataset.action;
 switch(id){
 case'close':close();break;
 case'welcome-start':state.welcomed=true;save();close();render();break;
 case'navigate':editor?.finish();view=b.dataset.view;render();break;
 case'go-supplier':view='supplies';supplyTab='buy';close();render();break;
 case'select-type':if(!J.typeAvailable(state,b.dataset.type)){showSkill('mounts');break;}selectedType=b.dataset.type;template='oval';render();break;
 case'template':template=b.dataset.template;render();break;
 case'start-design':resetEditor();action(()=>J.startDesign(state,selectedType,template,selectedMetal));break;
 case'editor-tool':editor.setTool(b.dataset.tool);editorOptions.tool=editor.tool;updateEditor();break;
 case'zoom-in':editor.changeZoom(editor.zoom*1.3);break;
 case'zoom-out':editor.changeZoom(editor.zoom/1.3);break;
 case'zoom-reset':editor.resetZoom();break;
 case'symmetry':editor.symmetry=!editor.symmetry;editorOptions.symmetry=editor.symmetry;renderToolOptions();break;
 case'undo':case'redo':editor.finish();J.undo(state,id==='redo');editor.syncSelection();save();editor.dirty=true;editor.metrics=J.evaluate(state.draft.design);updateEditor();renderToolOptions();$('#jewel-name').value=state.draft.design.name;break;
 case'editor-help':editorHelp();break;
 case'material-picker':showMaterials();break;
 case'apply-metal':editAndRefresh(d=>{d.metal=b.dataset.metal;});close();break;
 case'remember':try{editor.finish();J.remember(state);save();toast('Модель сохранена. Можно создать новый экземпляр.');}catch(e){toast(e.message,true);}break;
 case'finish-design':{const item=action(()=>J.complete(state));if(item){itemIndex=0;showAssessment(item,true);audio.play('magic');}break;}
 case'completed-shop':view='shop';close();render();break;
 case'completed-studio':view='studio';close();render();break;
 case'discard':modal('Убрать заготовку?',`<p>Рисунок текущей заготовки будет удалён. Материалы ещё не потрачены.</p>${btn('confirm-discard','Убрать заготовку','primary danger')}`);break;
 case'confirm-discard':action(()=>{state.draft=null;});close();break;
 case'load-model':action(()=>{J.restoreModel(state,b.dataset.model);view='studio';resetEditor();});break;
 case'inventory':showInventory();break;
 case'buyer':buyerId=b.dataset.buyer;render();break;
 case'policy':policy=b.dataset.policy;render();break;
 case'previous':case'next':itemIndex=(itemIndex+(id==='next'?1:-1)+state.stock.length)%state.stock.length;render();break;
 case'sell':action(()=>J.sell(state,b.dataset.item,currentBuyer()?.id,policy),q=>q.saturated?`Продано за ${q.price} ◈. Спрос на этот дизайн насыщен.`:`Продано за ${q.price} ◈`);audio.play('coin');break;
 case'demand-info':showDemand();break;
 case'item-info':{const item=state.stock.find(i=>i.id===b.dataset.item);if(item)showAssessment(item);break;}
 case'save-item-model':action(()=>J.rememberItem(state,b.dataset.item),'Модель сохранена.');break;
 case'recycle':modal('Разобрать изделие?',`<p>Все камни и 70% металла вернутся в запасы. Готовая оправа и работа будут разобраны.</p>${btn('confirm-recycle','Разобрать','primary danger',`data-item="${b.dataset.item}"`)}`);break;
 case'confirm-recycle':action(()=>J.recycle(state,b.dataset.item),'Материалы возвращены.');close();break;
 case'supply-tab':supplyTab=b.dataset.tab;render();break;
 case'buy':action(()=>J.buy(state,b.dataset.material,Number(b.dataset.count)),'Материалы в запасе.');break;
 case'locked-material':showSkill(['gold','diamond'].includes(b.dataset.material)?'gold':'alchemy');break;
 case'gather':action(()=>J.gather(state,b.dataset.area),r=>`Найдено: ${J.GEMS[r.gem].name} и ${J.METALS[r.metal].name} ×3`);break;
 case'next-day':action(()=>J.nextDay(state),`Открыт новый день. Черновик сохранён.`);break;
 case'prepare-order':if(state.draft){view='studio';render();toast('Сначала закончи или убери текущую заготовку.');}else{selectedType=b.dataset.type;resetEditor();action(()=>{J.startDesign(state,selectedType,'oval','copper');view='studio';});}break;
 case'deliver':action(()=>J.deliver(state,b.dataset.request,b.dataset.item),n=>`Заказ выполнен · ${n} ◈ · +16 опыта`);break;
 case'skill':showSkill(b.dataset.skill);break;
 case'learn':action(()=>J.learn(state,b.dataset.skill),'Новая техника изучена.');close();break;
 case'toggle-sound':state.sound=!state.sound;audio.setOptions(state);save();menu();break;
 case'toggle-music':state.music=!state.music;audio.setOptions(state);save();menu();break;
 case'export':editor?.finish();download(loadError?sourceRaw:J.serialize(state),`siyanie-day-${state.day}.json`);break;
 case'legacy-export':download(JSON.stringify(state.legacy),'pix-original-archive.json');break;
 case'import':$('#import-file').click();break;
 case'confirm-import':if(pendingImport){editor?.destroy();editor=null;state=pendingImport;pendingImport=null;loadError=false;state.welcomed=true;view='studio';buyerId=null;itemIndex=0;resetEditor();save();close();render();toast('Сохранение загружено.');}break;
 case'reset-recovery':modal('Новое сохранение',`<p>Сначала скачай повреждённый исходный файл через меню. Новый прогресс заменит его на этом устройстве.</p>${btn('confirm-reset','Создать новое сохранение','primary danger')}`);break;
 case'confirm-reset':state=J.newGame(Date.now()>>>0);loadError=false;sourceRaw=null;save();close();render();welcome();break;
 }
});
document.addEventListener('input',e=>{
 if(e.target.id==='brush-width'&&editor)editor.setWidth(e.target.value);
 if(e.target.id==='volume'){state.volume=Number(e.target.value);audio.setOptions(state);save();}
});
document.addEventListener('change',e=>{
 if(e.target.id==='start-metal')selectedMetal=e.target.value;
 if(e.target.id==='brush-width'&&editor&&editor.tool==='stone')editor.changeStone({size:editor.width+1.5});
 if(e.target.id==='gem-kind'&&editor){editor.gem=e.target.value;editor.changeStone({kind:editor.gem});}
 if(e.target.id==='gem-cut'&&editor){editor.cut=e.target.value;editor.changeStone({cut:editor.cut});}
 if(e.target.id==='jewel-name'&&editor)editAndRefresh(d=>{d.name=e.target.value.trim().slice(0,48)||typeName(d.type);});
});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>64000000)throw new J.AtelierError('Файл слишком большой.');pendingImport=J.deserialize(await file.text());modal('Загрузить эту мастерскую?',`<p>День ${pendingImport.day} · ${pendingImport.gold} монет · ${pendingImport.stock.length} изделий · ${pendingImport.library.length} моделей.</p><p class="fine-print">Текущий прогресс на устройстве будет заменён. Можно предварительно скачать его через меню.</p>${btn('confirm-import','Загрузить','primary')}`);}catch(error){toast(error.message,true);}e.target.value='';});
$('#menu-button').addEventListener('click',menu);
$('#end-day').addEventListener('click',()=>action(()=>J.nextDay(state),'Новый день. Эскиз и история действий сохранены.'));
dialog.addEventListener('cancel',e=>{if(!state.welcomed&&!loadError)e.preventDefault();});
document.addEventListener('keydown',e=>{if(!editor||dialog.open||e.target.matches('input,select,textarea'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const b=$(`[data-action="${e.shiftKey?'redo':'undo'}"]`);b?.click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){editor?.finish();save();audio.pause();}else{lastFrame=performance.now();audio.resume();if(editor)editor.dirty=true;}});
window.addEventListener('pagehide',()=>{editor?.finish();save();audio.pause();});
render();requestAnimationFrame(frame);if(!state.welcomed&&!loadError)welcome();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
