let dbPromise=null,queue=Promise.resolve();
function db(){return dbPromise??=new Promise((resolve,reject)=>{if(!globalThis.indexedDB){reject(new Error('IndexedDB недоступна'));return;}const open=indexedDB.open('pix-jewel-atelier',1);open.onupgradeneeded=()=>open.result.createObjectStore('saves');open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error);});}
// The save and its stamp {at,tab} are read and written in one transaction, so tabs see consistent pairs.
export async function loadAtelier(){const conn=await db();return new Promise((resolve,reject)=>{const tx=conn.transaction('saves','readonly'),store=tx.objectStore('saves'),main=store.get('main'),stamp=store.get('stamp');tx.oncomplete=()=>resolve({raw:main.result||null,stamp:stamp.result||null});tx.onabort=()=>reject(tx.error);});}
export class StaleTabError extends Error{constructor(stamp){super('Игра открыта в другой вкладке.');this.name='StaleTabError';this.stamp=stamp;}}
// Another tab that saved after the stamp this tab knows about wins: the write is refused, nothing is lost there.
export function saveAtelier(raw,{at=0,tab='',since=0}={}){const pending=queue.catch(()=>{}).then(async()=>{const conn=await db();return new Promise((resolve,reject)=>{const tx=conn.transaction('saves','readwrite'),store=tx.objectStore('saves'),req=store.get('stamp');let stale=null;req.onsuccess=()=>{const v=req.result;if(v&&v.tab!==tab&&v.at>since){stale=v;tx.abort();return;}store.put(raw,'main');store.put({at,tab},'stamp');};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(stale?new StaleTabError(stale):tx.error||new Error('Запись не удалась'));});});queue=pending;return pending;}
// The workshop that an import or a fresh start replaces waits under its own key until the player brings it back.
const BACKUP='before-import';
export function saveBackup(raw,meta){const pending=queue.catch(()=>{}).then(async()=>{const conn=await db();return new Promise((resolve,reject)=>{const tx=conn.transaction('saves','readwrite'),store=tx.objectStore('saves');store.put(raw,BACKUP);store.put(meta,BACKUP+':meta');tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error||new Error('Запись не удалась'));});});queue=pending;return pending;}
export async function loadBackup(full=true){const conn=await db();return new Promise((resolve,reject)=>{const tx=conn.transaction('saves','readonly'),store=tx.objectStore('saves'),meta=store.get(BACKUP+':meta'),raw=full?store.get(BACKUP):null;tx.oncomplete=()=>resolve(meta.result?{meta:meta.result,raw:raw?.result??null}:null);tx.onabort=()=>reject(tx.error);});}
