import * as G from './game.js';
import {portraitURL} from './art.js';

export function shopStockView(state,{buyerId,itemIndex,policy},{btn,icon,esc}) {
  const guests=state.customers.filter(c=>!c.served),buyer=guests.find(c=>c.id===buyerId)||guests[0],event=G.demandEvent(state);
  let html=`<div class="shop-tabs segmented">${[['stock','Витрина'],['materials','Материалы'],['trade','Караван'],['interior','Интерьер']].map(([id,name])=>btn('shop-tab',name,id==='stock'?'active':'',`data-tab="${id}"`)).join('')}</div>`;
  html+=`<div class="shop-visitors"><div class="buyer-strip">${guests.map(c=>{const p=G.CLIENTS.find(p=>p.id===c.client);return btn('select-buyer',`<img src="${portraitURL(p)}" alt=""><strong>${p.name}</strong>`,`buyer-chip${c.id===buyer?.id?' selected':''}`,`data-buyer="${c.id}" aria-label="Покупатель ${p.name}"`);}).join('')}</div>${btn('invite','+','invite-compact',`aria-label="Пригласить покупателя за 1 силу" ${state.invitedToday>=3||state.energy<1?'disabled':''}`)}</div>`;
  if(buyer){const p=G.CLIENTS.find(p=>p.id===buyer.client);html+=`<div class="buyer-compact"><div class="buyer-needs"><b>${p.name}</b><span>${buyer.greeted?`${buyer.trait} · качество ${buyer.quality}+`:'Познакомиться?'}</span>${btn('buyer-info','?','info-button','aria-label="Предпочтения покупателя"')}</div>${buyer.greeted?'':`<div class="greeting-row">${btn('greet',`${icon('handshake')}Нужды`,'secondary','data-approach="needs"')}${btn('greet',`${icon('anvil')}Ремесло`,'secondary','data-approach="craft"')}</div>`}</div>`;}
  else html+=`<div class="buyer-compact"><span>Гости вернутся утром.</span></div>`;
  if(state.stock.length){const item=state.stock[itemIndex],quote=buyer?G.customerQuote(state,item,buyer.id,policy):null;
    html+=`<div class="showcase compact-showcase" id="showcase" aria-label="Пролистываемая витрина"><div class="carousel-stage">${btn('item-prev','‹','carousel-arrow','aria-label="Предыдущий товар"')}<div class="showcase-item">${icon(item.recipe,G.MATERIALS[item.material].color)}<span class="display-shadow"></span></div><div class="showcase-description"><h2>${G.itemName(item)}</h2><span class="item-quality">★ ${item.quality}</span><span class="showcase-counter">${itemIndex+1}/${state.stock.length}</span></div>${btn('item-next','›','carousel-arrow','aria-label="Следующий товар"')}</div><div class="traits">${G.itemTraits(item).map(t=>`<span class="trait">${t}</span>`).join('')}</div><div class="segmented price-policy">${[['quick','Быстро'],['fair','Обычно'],['premium','Дороже']].map(([id,name])=>btn('policy',name,policy===id?'active':'',`data-policy="${id}"`)).join('')}</div>${quote?`<div class="sale-row">${btn('serve',`${icon('coin')}Продать · ${quote.price} ◈`,'primary',quote.accepted?'':'disabled')}${state.skills.includes('negotiation')&&buyer.greeted?btn('haggle','↗','haggle-compact','aria-label="Торговаться"'):''}</div>${quote.reason?`<p class="quote-hint">${esc(quote.reason)}</p>`:''}`:''}</div>`;
  }else html+=`<div class="shop-empty">${icon('shop')}<div>На витрине пока пусто.</div>${btn('navigate','Создать изделие','primary','data-view="forge"')}</div>`;
  html+=btn('demand-info',`${icon('star')}${event.name}`,'demand-compact','aria-label="Сегодняшний спрос"');
  return html;
}
