import * as G from './game.js';
import {targetZone} from './crafting.js';
import {finishProgress} from './interactions.js';
export function workConsole(s,t,busy,{btn,icon}){
  const w=s.work,stage=G.workStage(s),hint=['Две метки задают форму. Меть в зелёной зоне.','Удерживай меха. Отпусти в зелёной зоне.','Бей по светящейся точке. Следи за жаром.','Перетащи заготовку в выбранную среду.','Закрепи три детали.'][w.step];
  let body='';
  if(w.step<3){
    const action=['work-mark','heat-press','work-hit'][w.step],label=['Нанести метку','Держать меха','Ударить'][w.step],count=w.step===0?2:5;
    body=`<div class="work-meter"><div class="meter" role="meter" aria-label="${stage.name}: точность" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="meter-target" id="meter-target"></div><div class="meter-fill" id="meter-fill"></div><div class="meter-cursor" id="meter-cursor"></div></div></div>`;
    if(w.step!==1)body+=`<div class="hit-dots" id="hit-dots">${'<span></span>'.repeat(count)}</div>`;
    if(w.step===2)body+=`<div class="forging-status"><span id="heat-state">Металл горячий</span><div class="thermal-bar" aria-label="Жар заготовки"><i id="thermal-fill" style="width:${t.temperature*100}%"></i></div><span id="combo-count">${t.combo?`×${t.combo}`:t.profile.name}</span></div><div class="forge-zones" id="forge-zones">${[0,1,2].map(i=>btn('forge-zone',`${icon('hammer')}<span>${i+1}</span>`,`forge-zone${i===targetZone(t)?' target':''}`,`data-zone="${i}" aria-label="Удар по точке ${i+1}${i===targetZone(t)?', нужная точка':''}" ${busy?'disabled':''}`)).join('')}</div>`;
    body+=btn(action,'<canvas id="workpiece" width="360" height="150" role="img" aria-label="Изделие, форма металла и рабочий инструмент"></canvas>','work-board',`aria-label="${label}: прямо на заготовке" ${busy?'disabled':''}`);
    body+=`<div class="work-controls">${btn(action,`${icon(stage.icon)}${label}`,'primary'+(w.step===1?' hammer-button':''),`id="work-control" ${busy?'disabled':''}`)}${w.step===2?btn('reheat',icon('fire'),'reheat-button',`aria-label="Подогреть металл у горна" title="Подогреть" ${busy?'disabled':''}`):''}${btn('stage-assist','✦','stage-assist',`aria-label="Помощь мастера: выполнить этот этап" title="Помощь мастера" ${busy?'disabled':''}`)}</div>`;
  }else if(w.step===3){
    body=`<div class="quench-workspace"><button class="quench-handle" id="quench-handle" aria-label="Перетащи горячую заготовку в воду, воздух или масло" ${busy?'disabled':''}>${icon(w.recipe,'#ffad5b')}<span>↙ ↓ ↘</span></button><div class="quench-basins">${[['water','Вода','barrel','Качество'],['air','Воздух','wind','Лёгкость'],['oil','Масло','fire','Острота · 3 ◈']].map(([id,name,i,trait])=>btn('quench',`${icon(i)}<strong>${name}</strong><small>${trait}</small>`,'quench-basin',`data-method="${id}" ${busy||(id==='oil'&&(!s.equipment.barrel||!s.skills.includes('hardening')||s.gold<3))?'disabled':''}`)).join('')}</div></div>`;
  }else{
    const options=G.finishOptions(s),method=t.finishMethod,plain=method==='plain',stamps=G.stampOptions(s);
    if(options.length>1)body+=`<div class="finish-options segmented">${options.map(o=>btn('finish-method',o.name,method===o.id?'active':'',`data-method="${o.id}" ${busy?'disabled':''}`)).join('')}</div>`;
    if(stamps.length>1)body+=`<div class="stamp-row" aria-label="Клеймо мастерской"><span>Клеймо</span>${stamps.map(m=>btn('work-stamp',icon(m.icon),`stamp-choice${(w.mark||'none')===m.id?' active':''}`,`data-stamp="${m.id}" aria-label="${m.name}" title="${m.name}" ${busy?'disabled':''}`)).join('')}</div>`;
    body+=`<div class="finish-pad" id="finish-pad" data-method="${method}" aria-label="${plain?'Закрепи три детали':'Води пальцем по поверхности изделия'}">${icon(w.recipe,G.MATERIALS[w.material].color)}${plain?`<div class="rivet-row">${[0,1,2].map(i=>btn('finish-rivet',t.rivets.includes(i)?'✓':'+',`rivet${t.rivets.includes(i)?' done':''}`,`data-rivet="${i}" aria-label="Закрепить деталь ${i+1}" ${busy||t.rivets.includes(i)?'disabled':''}`)).join('')}</div>`:'<span class="rub-arrow">⇆</span>'}<div class="finish-progress"><i id="finish-progress" style="width:${finishProgress(t)*100}%"></i></div></div>${btn('finish-tap',plain?'Закрепить деталь':'Обработать поверхность','primary',`id="work-control" ${busy?'disabled':''}`)}`;
  }
  return `<div class="work-console"><div class="work-path">${G.WORK_STAGES.map((stage,i)=>`<div class="work-step${i<w.step?' done':''}${i===w.step?' current':''}" aria-label="${stage.name}">${icon(stage.icon)}<span>${i+1}</span></div>`).join('')}</div><div class="work-title"><h2>${stage.name} <small>· ${G.recipeById(w.recipe).short}</small></h2>${btn('cancel-work-ask','×','work-cancel','aria-label="Убрать заготовку"')}</div><p class="work-hint" id="work-hint">${busy?(t.reheating?'Подогрев у горна…':'Мастер подходит…'):w.step===4&&t.finishMethod!=='plain'?'Води пальцем по изделию, чтобы обработать его.':hint}</p><div class="work-body">${body}</div><div class="work-busy" ${busy?'':'hidden'}><span></span> Мастер работает</div></div>`;
}
